### ISSUE TITLE
Folder / Project - make folder and org id a resourceRef (external or direct)

### ISSUE THREAD

**Issue by tedelwartowski-bestbuy** [GoogleCloudPlatform/k8s-config-connector#349] opened 2020-12-17 15:58 UTC
This enhancement request is similar to what has been requested in #181 however I would like to propose changing how the reference to a folder or org id is handled in both a Folder and Project resource. Currently, reference to a folder or org id is handled via an annotation which makes it hard to maintain referential relationships between folders and projects. I would like to propose switching the reference of the folder or org id to be a **resourceRef** (external or direct) such that we can then maintain a referential hierarchy directly with our config connector manifests. Without this, maintaining relationships between folders and projects is manually intensive and impedes on our ability to properly implement automation for the platform.

**Comment by spew** [comment] 2020-12-17 20:19
Thanks @tedelwartowski-bestbuy for this suggestion. What you described is the direction we want to take the product with eventually de-emphasizing the annotation.

**Comment by tedelwartowski-bestbuy** [comment] 2020-12-17 20:50
@spew - thank you for confirming this is something for consideration on the product roadmap. I believe #181 would still be relevant as an interim solution until what has been proposed here can be implemented.

**Comment by spew** [comment] 2020-12-17 21:00
We are looking into accelerating the timeline on #181 @jcanseco for visibility

**Comment by travisrandolph-bestbuy** [comment] 2021-01-20 20:02
@spew @jcanseco Has there been any progress on this feature?

**Comment by jcanseco** [comment] 2021-01-20 20:12
Hi @travisrandolph-bestbuy and @tedelwartowski-bestbuy, yes this is something we're working on actively. There's a design undergoing internal review right now meant to address the particular problem described in this issue. We'll let you know when we have more updates on progress.

**Comment by jcanseco** [comment] 2021-03-25 21:32
Hi all, we've added support for `folderRef` and `organizationRef` references in `Project` and `Folder` in **1.43.0** which should give you the ability to reference `Folder` resources by name.

Please note, however, that there is a known issue where you will not be able to delete a `Folder` and its child resources at the same time. Otherwise, the deletion will get stuck. You must either delete the parent `Folder` first and wait for it to be gone from the K8s API Server or delete the child resources first. See the `Warning` [here](https://cloud.google.com/config-connector/docs/reference/resource-docs/resourcemanager/folder) for more details. We intend to look into how to fix this issue in the future to remove the need to order your deletions.

Also note that the `folder-id` and `organization-id` annotations for `Project` and `Folder` are now deprecated as a result. To migrate `Project` and `Folder` resources across folders/orgs, please update the `folderRef` or `organizationRef` fields instead. Note that migrations from folder to organization and vice versa are still not supported, however.

To maintain consistency across our resources, we intend to roll out support for `projectRef`, `folderRef`, and `organizationRef` in place of the `project-id`, `folder-id`, and `organization-id` annotations for our other resources over the next few weeks.

**Comment by yashsaini77** [comment] 2021-03-25 22:21
So when we want to create a project in a folder so in the manifest file of the project, how do we reference the folder id if we are trying to work in an automated way?

**Comment by yashsaini77** [comment] 2021-03-25 22:24
If we want to create a folder and then create a project under that folder then how do we reference the folder in the resource Project's manifest file here also remember we need the automation? @jcanseco 

apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    # Set this field after finding the folder number.
    cnrm.cloud.google.com/folder-id: "" 
    cnrm.cloud.google.com/auto-create-network: "false"
  name: kcc-dev 
spec:
  name: kcc-dev 
  billingAccountRef:
    # Replace "${BILLING_ACCOUNT_ID?}" with the numeric ID for your billing account
    external: ""

**Comment by jcanseco** [comment] 2021-03-25 22:33
Here's an example:
```yaml
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  name: my-project
spec:
  name: My Project
  folderRef:
    name: my-folder
  billingAccountRef:
    external: "AAAAA-BBBBB-CCCCC-DDDDD"
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: my-folder
spec:
  displayName: My Folder
  organizationRef:
    external: "123456789"
```

**Comment by yashsaini77** [comment] 2021-03-25 22:42
So both resources will be in the same manifest and the dependency will be done by itself like firstly folder will be created and then the project will be created under that folder. right? @jcanseco

**Comment by jcanseco** [comment] 2021-03-25 22:46
> the dependency will be done by itself like firstly folder will be created and then the project will be created under that folder. right? 

Yep that's correct @yashsaini77.

The `Project` and `Folder` don't _need_ to be in the same manifest file though. They can be in different files which you can `kubectl apply` separately.

**Comment by tonybenchsci** [comment] 2021-03-26 01:48
"Also note that the folder-id and organization-id annotations for Project and Folder are now deprecated as a result. "

@jcanseco This is unfortunate, as we actually worked out a nice directory structure using the annotation method. Is there no plan to keep both annotation and resourceRef working?

**Comment by jcanseco** [comment] 2021-03-26 03:51
Hi @tonybenchsci. Your set-up should continue to work just fine. We made sure to keep backwards compatibility in mind when developing this feature.

Here are the important points:
* Creating new resources with an annotation and without a reference will continue to work. We will just default a reference value for you based on the annotation. For example, if you create a folder-scoped resource with a `folder-id: 12345` annotation, we will default a `spec.folderRef.external: 12345` field for you.
* Creating new resources without an annotation or reference in a namespace that has an annotation will continue to work. We will just default a reference value for you based on the annotation. This will hold true even for future resources that never supported the annotation to begin with but do support the references.
* Existing resources that have an annotation and no reference will be given a reference value based on the annotation.

The only real behavioral change is the following:
* If you want to migrate a `Project`/`Folder` resource across folders/orgs, you must update the `folderRef`/`organizationRef` field instead of the `folder-id`/`organization-id` annotation, since annotations are ignored once a resource has a reference.
* The above also means that you can choose to remove the annotations from your resources once they have a reference if desired.

> Doesn't that mean that the entire doc section in https://cloud.google.com/config-connector/docs/how-to/organizing-resources/overview will be obsolete in a few weeks?

Sort of, and we do plan to update it. Most of it still holds true though. The key difference is that the source of truth for which project/folder/organization a resource belongs to is now the resource's `projectRef`/`folderRef`/`organizationRef` rather than the resource's `project-id`/`folder-id`/`organization-id` annotation.

Before, namespace-level annotations were used to default resource-level annotations. Now, namespace-level annotations will be used to default references on the resource.

@tonybenchsci I hope that alleviates the concerns somewhat. Please let me know if you have any other questions. We really made sure to sink in time to ensure backwards compatibility as much as we can.

**Comment by tonybenchsci** [comment] 2021-03-26 13:54
@jcanseco Thank you for the excellent explanation. We'll be upgrading now with the assurance of backwards compatibility; also acknowledging that migrating these resources in the future requires updating the new source-of-truth `resourceRef`

**Comment by jcanseco** [comment] 2021-04-02 01:20
Hi @tonybenchsci, we recommend delaying an upgrade for now. We just detected an issue where the defaulting of references doesn't quite work when applying resources with `--server-side` (the default in K8s 1.18+).

You should not have the problem if you're not applying resources with `--server-side` and if you're using an older version of K8s than 1.18, but that may be unlikely since K8s 1.18 is now the default for the `REGULAR` channel in GKE.

We're working on a fix at the moment and will put out an update soon. Note that the only resources affected are `Project` and `Folder` as we have not yet rolled out references support for other resources.

Note that only the defaulting of references is affected. There is no problem if you explicitly specify the references yourself, but this obviously is not an easy option for users who are relying on the namespace defaulting behavior.

**Comment by tonybenchsci** [comment] 2021-04-08 17:42
@jcanseco Thanks but I already upgraded at the time of my last comment :) 
We're on `1.17.17-gke.1101 ` in STABLE channel, so hopefully your patch timing works out.

**Comment by jcanseco** [comment] 2021-04-08 17:44
Hi @tonybenchsci, yep we've put out a fix in **KCC 1.45.0**.

**Comment by tonybenchsci** [comment] 2021-04-19 20:43
Thanks @jcanseco 
BTW, the documentation (e.g. https://cloud.google.com/config-connector/docs/reference/resource-docs/bigquery/bigquerydataset) says `projectRef` is "Required". Shouldn't it be optional? (because "Creating new resources with an annotation and without a reference will continue to work. ")

Another point: While we rely on `cnrm.cloud.google.com/organization-id` annotation for `kind: Project`, we actually mostly rely on the default behaviour of KCC namespace == GCP project_id which has neither annotations nor projectRef for resources we create in a GCP-project-named namespace. I assume this will also continue to work?

**Comment by jcanseco** [comment] 2021-04-19 21:30
> Shouldn't it be optional?

Yes this is docs improvement we can consider. I was thinking it'd make sense to link to the docs on how to set up default projects/folders/orgs via namespace annotations, once we get around to updating those docs :)

> we actually mostly rely on the default behaviour of KCC namespace == GCP project_id which has neither annotations nor projectRef for resources we create in a GCP-project-named namespace. I assume this will also continue to work?

Yes that will continue to work (and is something we test).

**Comment by tonybenchsci** [comment] 2021-04-26 21:33
@jcanseco We've upgraded to v1.47.0, but now get `spec.projectRef: Required value` For BigQueryDataset resources. 
Is this intended? It wasn't required before because it was created in a namespace that is equal to the GCP project_id that the BQ dataset was created in.

**Comment by jcanseco** [comment] 2021-04-27 00:06
Hey @tonybenchsci, to confirm, are you saying you cannot create `BigQueryDataset` resources (without either the `projectRef` reference or `project-id` annotation) in namespaces without the `project-id` annotation?

**Comment by tonybenchsci** [comment] 2021-04-27 03:53
Thanks for getting back to me @jcanseco . I should've given more information in my last comment :-) 

1. ```
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  name: bsmining
  owner: datarun
spec:
  description: "Data Extraction Pipeline Dataset"
  friendlyName: bsmining
  location: US
```
2. Error message is `The BigQueryDataset "bsmining" is invalid: spec.projectRef: Required value`
3. Coming from kubectl apply --dry-run=server

This resource has been created months ago where kubectl apply would always return `unchanged` in our GitOps CICD pipeline. Now we're getting the error, which means backwards-compatibility is not satisfied (in this sense the documentation "mistake" is actually not a mistake). Is the only workaround to add `spec.projectRef`?

**Comment by jcanseco** [comment] 2021-04-27 19:10
Thanks @tonybenchsci . It's interesting that the `BigQueryDataset` on the API server didn't have a `spec.projectRef` defaulted.

Can you scan through the controller's logs and see if there are any errors?

```
kubectl logs -f -n cnrm-system cnrm-controller-manager-0
```

**Comment by tonybenchsci** [comment] 2021-04-27 19:18
Well we have 100s of resources across many projects. So if I do `kubectl logs -n cnrm-system cnrm-controller-manager-0 -c manager | grep bigquerydataset` I'm now seeing way more failures than I anticipated. 

Many of them are `invalid: spec.projectRef: Required value` while some are `successfully finished reconcile`

**Comment by jcanseco** [comment] 2021-04-27 20:08
Gotcha, could you search for any of the following strings:
1. `error applying changes to resource`
2. `error ensuring resource`
3. `error with status update call to API server`

My suspicion is that the controller is failing to add the `spec.projectRef` to the existing `BigQueryDataset` resources as would be expected.

**Comment by jcanseco** [comment] 2021-04-27 20:59
To unblock yourself (i.e. abandon all your `BigQueryDataset` resources), you can follow these steps:

1. Disable the operator temporarily (so that it doesn't reset the changes we're about to make to the `BigQueryDataset` CRD):
    ```shell
    kubectl edit statefulset -n configconnector-operator-system configconnector-operator
    # Set spec.replicas to 0, then save and quit.
    ```

2. Modify the `BigQueryDataset` CRD to not require `spec.projectRef`:
    ```shell
    kubectl edit crd bigquerydatasets.bigquery.cnrm.cloud.google.com
    # Delete the field `spec.versions[].schema.openAPIV3Schema.properties.spec.required`
    # Note that there is only one element under `versions[]`, so you only need to remove one `required` field.
    ```
3. Verify that `BigQueryDataset` no longer requires `projectRef`:
    ```shell
    kubectl get crd bigquerydatasets.bigquery.cnrm.cloud.google.com -o jsonpath="{.spec.versions[].schema.openAPIV3Schema.properties.spec.required}"
    # Should return nothing
    ```
3. Try abandoning your `BigQueryDataset` resources. If that doesn't work, [try deleting the finalizers](https://cloud.google.com/config-connector/docs/troubleshooting#forced-cleanup).

4. Re-enable the operator:
    ```shell
    kubectl edit statefulset -n configconnector-operator-system configconnector-operator
    # Set spec.replicas to 1, then save and quit.
    ```

5. Confirm that `BigQueryDataset` requires `spec.projectRef` again (after a few minutes):
    ```shell
    kubectl get crd bigquerydatasets.bigquery.cnrm.cloud.google.com -o jsonpath="{.spec.versions[].schema.openAPIV3Schema.properties.spec.required}"
    # Should return:
    # ["projectRef"]
    ```

**Comment by tonybenchsci** [comment] 2021-04-27 22:12
Thanks @jcanseco , but doesn't this just abandon all the BigQueryDatasets? We want to manage them.
Is this a real bug for which a fix will be released?

**Comment by jcanseco** [comment] 2021-04-27 22:17
Ah yes, I provided steps for abandonment in case you needed them (e.g. if you're getting spammed by errors and just wish for them to stop).

> Is this a real bug for which a fix will be released?

Yes, it could be a real bug so we're currently trying to reproduce the issue, but so far we haven't had any luck, so we're continuing to investigate.

If we can reproduce it, we will try to get a fix out ASAP since this would be considered a high-priority issue.

**Comment by tonybenchsci** [comment] 2021-04-27 22:21
> Gotcha, could you search for any of the following strings:
> 
>     1. `error applying changes to resource`
> 
>     2. `error ensuring resource`
> 
>     3. `error with status update call to API server`
> 
>     4. `error with update call to API server`
> 
> 
> My suspicion is that the controller is failing to add the `spec.projectRef` to the existing `BigQueryDataset` resources as would be expected.

All of them are of the type:

`{"severity":"error","logger":"controller-runtime.manager.controller.bigquerydataset-controller","msg":"Reconciler error","reconciler group":"bigquery.cnrm.cloud.google.com","reconciler kind":"BigQueryDataset","name":"REDACTED","namespace":"REDACTED","error":"error with status update call to API server: BigQueryDataset.bigquery.cnrm.cloud.google.com \"REDACTED\" is invalid: spec.projectRef: Required value"}`

**Comment by jcanseco** [comment] 2021-04-27 22:52
Thanks @tonybenchsci! That last comment helped us reproduce the issue. We'll work on a fix and update this thread accordingly.

**Comment by tonybenchsci** [comment] 2021-04-28 03:54
I see https://github.com/GoogleCloudPlatform/k8s-config-connector/commit/425105a0804478e997033f2620faf6d49cbacc17#diff-1af49b3a99aea8b1e3f1fd77a839df6cc1e5ff3d8473497421d3d77296c3d828R238 for v1.48.0 😄 

Is that the fix?

**Comment by tonybenchsci** [comment] 2021-04-28 15:35
I'm guessing 1.48.0 doesn't have a fix, right?

**Comment by jcanseco** [comment] 2021-04-28 19:35
Hi @tonybenchsci, unfortunately no. We're working on a fix at the moment and will put out a patch release if we can get it in this week. We'll update you when that happens.

**Comment by jcanseco** [comment] 2021-04-30 00:38
Hi @tonybenchsci, we just released a fix in 1.49.0. Could you try it out and let us know if it works for you?

**Comment by tonybenchsci** [comment] 2021-04-30 13:42
Great thanks @jcanseco 
I see 1.49.0 on the releases page, but it seems incomplete, and it's not seen in `gsutil ls gs://configconnector-operator` yet.

**Comment by caieo** [comment] 2021-04-30 17:55
@tonybenchsci, sorry for the delay in updating our release documentation and our operator. We'll have the operator storage bucket updated in a few hours!

**Comment by caieo** [comment] 2021-04-30 19:12
@tonybenchsci, 1.49.0 should now be up in `gs://configconnector-operator/`, please let us know if the fix works for you.

**Comment by tonybenchsci** [comment] 2021-04-30 22:10
@caieo @jcanseco It worked after 1.49.0 thanks.
We're now stuck in a deletion state because of previous attempts that got unblocked as a result of the fix. 

```
message: 'Delete call failed: error deleting resource: [{0 Error when reading
      or editing Dataset: googleapi: Error 400: Dataset b6i-stg:bsmining is still
      in use, resourceInUse  []}]'
    reason: DeleteFailed
    status: "False"
```
There must be a kubectl command to cancel a delete...

**Comment by jcanseco** [comment] 2021-05-03 17:16
Hi @tonybenchsci, great, happy to hear your issue has been resolved!

**Comment by tonybenchsci** [comment] 2021-05-27 14:56
@jcanseco Is this expected? `admission webhook "deny-immutable-field-updates.cnrm.cloud.google.com" denied the request: error validating container annotations: cannot add/change container annotation cnrm.cloud.google.com/folder-id as it is no longer supported by the resource; set one of [spec.folderRef, spec.organizationRef] instead.`

We actually expected the folder-id annotation on a "kind: Project" to still be able to override the namespace level org-id annotation. And then have it do the automatic defaulting of folderRef, just like how the organizationRef is defaulted via the org-id annotation.

**Comment by jcanseco** [comment] 2021-05-27 19:00
Hi @tonybenchsci, yes that is expected behavior. Unfortunately, certain cases become quite complex and confusing from a UX perspective by continuing to allow mutations of container annotations, so it was decided to go for a "stop the bleeding" approach by making container annotations immutable. Note that container annotations had been mutable for only `Project` and `Folder` since they could be migrated across parent resources.

As a side-note: we do allow _removal_ of container annotations once the resource has a hierarchical reference. This is done to allow users to prevent other people from potentially being confused by seeing both an annotation and a reference on a resource.

**Comment by travisrandolph-bestbuy** [comment] 2021-11-15 17:09
@jcanseco We are ready to close this issue. We have moved our Folders over to the org/folder refs.

**Comment by maqiuyujoyce** [comment] 2021-11-15 18:32
Thanks for confirming, @travisrandolph-bestbuy !

**Closed by maqiuyujoyce** 2021-11-15 18:32 UTC
Labels: enhancement
