### ISSUE TITLE
Not able to delete default compute engine service account by KCC

### ISSUE THREAD

**Issue by yashsaini77** [GoogleCloudPlatform/k8s-config-connector#341] opened 2020-12-09 22:31 UTC
I want to delete the default compute engine service account so I tried acquiring the default compute engine service account using this YAML to delete it and applied it on the GKE cluster and it got applied but then I try to delete it but the resource doesn't get deleted but it should have.

**apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
     cnrm.cloud.google.com/project-id: $PROJECT_ID
  labels:
     label-one: "value-one"
  name: 211111110957-compute@developer.gserviceaccount.com   
spec:
    displayName: Compute Engine default service account**

**Comment by caieo** [comment] 2020-12-10 18:32
Hi @yashsaini77, ConfigConnector can only acquire existing ServiceAccounts with the format  `{{account_id}}@{{project}}.iam.gserviceaccount.com` where `account_id` would be the name of your SA and the email after the @ sign is generated (you don't need to include it in the resource name). For now, ConfigConnector doesn't support acquiring generated service accounts, but it is something we are considering in the future. Please check #340 for updates on this feature.

**Comment by yashsaini77** [comment] 2020-12-10 19:00
I am able to acquire the custom service account which I created by myself but I am not able to acquire the default compute service account which gets created itself not by us and the default compute service account's name looks like this only 
 211111110957-compute@developer.gserviceaccount.com so are you saying we can't acquire the automatically created compute engine default service acccount but we can acquire our manually created custom service account like (kcc-serviceaccount@abc.iam.gserviceaccount.com)?

**Comment by caieo** [comment] 2020-12-10 19:56
@yashsaini77 , Yep, that is exactly what I was saying in the comment above. Currently, Config Connector cannot acquire service accounts that do not follow the format of custom created service accounts.

**Comment by yashsaini77** [comment] 2020-12-11 14:42
**@caieo**, thank you! then you think there is no way to delete the compute default service account with KCC ?

**Comment by caieo** [comment] 2020-12-14 17:11
@yashsaini77, As I mentioned above, this has already been requested by another GH user in issue #340, please follow that thread for updates to this request in the future. Feel free to chime in on that thread with your use case and urgency to help us better understand when you need this enhancement by.

**Comment by spew** [comment] 2020-12-21 17:00
Closing as a duplicate of #340

**Closed by spew** 2020-12-21 17:00 UTC
Labels: bug
