### ISSUE TITLE
CloudSchedulerJob pubsubTarget data cannot be updated

### ISSUE THREAD

**Issue by erik-carlson** [GoogleCloudPlatform/k8s-config-connector#746] opened 2022-12-02 16:46 UTC
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

In a CloudSchedulerJob resource, the `pubsubTarget.data` field is not listed as immutable, but if the field is updated on an existing resource it goes into `updateFailed` with this message: 'Update call failed: error applying desired state: infeasible update: ({true <nil> PubsubTarget.Data}) would require recreation'

### Additional Diagnostic Information

na

### Kubernetes Cluster Version

1.23.12-gke.100

### Config Connector Version

1.96.0

### Config Connector Mode

namespaced mode (default)

### Log Output

'Update call failed: error applying desired state: infeasible update: ({true <nil> PubsubTarget.Data}) would require recreation'

### Steps to reproduce the issue

1. create a cloud scheduler job with `pubsubTarget.data` set
2. the cloud scheduler job gets created successfully
3. update the `pubsubTarget.data` field in the kcc resource
4. resource fails with the error above

### YAML snippets

```YAML
apiVersion: cloudscheduler.cnrm.cloud.google.com/v1beta1
 kind: CloudSchedulerJob
 metadata:
   name: testing
 spec:
   location: us-central1
   pubsubTarget:
     data: eyJmb28iOiAiYmF6In0K
     topicRef:
       name: foo
   schedule: 0 0 1 1 *
   timeZone: Etc/UTC
```

**Comment by justinsb** [comment] 2022-12-07 14:54
Thanks for the report - I'll look into it!

**Comment by travisrandolph-bestbuy** [comment] 2023-01-16 18:51
@justinsb it appears this issue isn't limited to pubsubTarget.data. We are also seeing this issue with all properties under RetryConfig for the CloudScheduler resource.
`message: 'Update call failed: error applying desired state: infeasible update:
        ({true <nil> RetryConfig.MaxBackoffDuration}) would require recreation'`

**Comment by maqiuyujoyce** [comment] 2023-01-20 00:30
@travisrandolph-bestbuy thank you for reporting the issue!

The CloudSchedulerJob CRD is generated based on the DCL resource schema (https://github.com/GoogleCloudPlatform/declarative-resource-client-library/blob/main/services/google/cloudscheduler/job.yaml) and that is where the issue comes from. We will work with DCL to figure out a solution.

**Comment by vgelot** [comment] 2023-01-25 14:41
Hi,
We have the same kind of issue with the `CloudSchedulerJob` resource for the `httpTarget`. 
The error is the following (Update call failed: error applying desired state: infeasible update: ({true <nil> HttpTarget.Uri}) would require recreation). And this field is not listed as immutable.
Current version for config connector: 1.96.0

**Comment by maqiuyujoyce** [comment] 2023-01-25 23:42
Hi @vgelot , thank you for sharing the error.

The error you received indicated the actual behavior of the API; the issue here is that the field is not correctly listed as immutable in the CRD. The issue is on our radar and will keep you posted when there are updates.

Just want to gather some information about the issue: Do you consider the fix a hard blocker, a friction point, or a nice-to-have?

**Comment by vgelot** [comment] 2023-01-30 10:42
Thanks @maqiuyujoyce, we will check if we fill up the information wrongly
We saw this error after updating config connector to 1.96.0, so thought it was the same error as this one

**Comment by maqiuyujoyce** [comment] 2023-01-31 01:56
Hi @vgelot , thank you for sharing the context! I used Google Console to update `httpTarget.Uri`, `pubsubTarget.data`, and `retryConfig` in the scheduler jobs, and they all worked fine. So I'll need to correct my last comment: The error message should probably be coming from DCL instead of the underlying GCP API; will work with the library team to do further investigation.

Meanwhile, I wondered how important is this issue to you: a hard blocker, a friction point, or a nice-to-have?

**Comment by vgelot** [comment] 2023-02-02 14:02
Hi,
I would say a "friction point", we have this error more often in our CI.
From a fresh PR, we won't have the error, but when making changes, we need to manually clean all the resources before redeploying it

**Comment by maqiuyujoyce** [comment] 2023-02-13 23:00
Thanks for sharing, @vgelot !

**Comment by erik-carlson** [comment] 2023-08-29 18:45
I'm not sure what fixed this or when, but I've retested updating the pubsub target data on 1.108.0 and this issue doesn't seem to exist anymore. I'm not sure about the other use cases that have been mentioned in other comments, so I'll leave the issue open for someone from google to determine if it should be closed.

**Comment by diviner524** [comment] 2023-08-29 20:26
@erik-carlson I took a quick look on the related change. This was actually caused by a bug in the underlying DCL library. The fix was done around April and release in Config Connector version 1.105.0. The fix should have solved similar issues for not just `pubsubTarget`, but other fields like `httpTarget` as well.

I will close this issue but feel free to reopen it if you still see similar problems in this resource.

**Closed by diviner524** 2023-08-29 20:26 UTC
Labels: bug
