### ISSUE TITLE
Customize Sync Time

### ISSUE THREAD

**Issue by ngeorgakopoulos-deloitte** [GoogleCloudPlatform/k8s-config-connector#625] opened 2022-03-08 03:12 UTC
**Customize sync time**

**nice-to-have**

When you deploy Cloud resources from a GKE Cluster through GCP Config Connector, if someone manually deletes the resource, it can take more than 10 minutes for the Config Connector controller to notice the change and start the sync process re-creating the resource.

Other controllers like Crossplane detect and reconcile in a couple of seconds..

Will be nice if we can reduce this sync time to be similar to Crossplane or have it customized by a value.

**Comment by xiaobaitusi** [comment] 2022-03-09 22:35
Hi @ngeorgakopoulos-deloitte, thanks for surfacing this enhancement request.

> Will be nice if we can reduce this sync time to be similar to Crossplane or have it customized by a value.

I can see the benefit of customized sync/re-reconcile interval. I'll bring it to team for discussion. 

Though there is one caveat that I think to mention: with short interval, it means more reading requests to the underlying API. One could run into quota limit issue when managing resources at scale. AFAIK, some service APIs have pretty restrictive quotas/limits. Do you think of having shorter sync time across the board or only on some critical resources?

**Comment by ngeorgakopoulos-deloitte** [comment] 2022-03-10 02:03
hi @xiaobaitusi , from my experience with Crossplane in AWS and GCP it seems much more beneficial of having the sync time in seconds than in minutes... I'm not sure if this is the same across the board or only to specific resources, if we want to follow the Kubernetes resource model, imagine how it looks when a Pod get's destroyed for whatever reason and it takes 10 minutes for kube controller to recover it ...

For sure shorter sync time across the board is required in my opinion, I'm not sure if it should be the same for all resources.

Do you know the service APIs that are restrictive ? I might be able to help with some testing..

**Comment by nicolas-g** [comment] 2022-03-10 17:07
this seems to be a duplicate of https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/509

**Comment by xiaobaitusi** [comment] 2022-03-10 18:38
> this seems to be a duplicate of https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/509

Hi @nicolas-g, you are right. They are for the same topic. Let's close this thread and centralize related discussion in one place. 

> Do you know the service APIs that are restrictive ? I might be able to help with some testing..

Hi @ngeorgakopoulos-deloitte , as mentioned in the duplicate issue, Spanner seems to be the known problematic one. [The rate limit for administrative actions is 5 per second per project per user (averaged over 100 seconds)](https://cloud.google.com/spanner/quotas#administrative_limits). I don't think that there will be a good one-size-fit-all reconciliation frequency across all services/resources, it goes back to your original request - configurable reconciliation frequency.

**Comment by xiaobaitusi** [comment] 2022-03-10 18:38
Let's continue the discussion in the other thread.

**Closed by xiaobaitusi** 2022-03-10 18:38 UTC
Labels: enhancement
