### ISSUE TITLE
BigTable GCPolicy Max Age Duration "d" (for days) is not working correctly

### ISSUE THREAD

**Issue by joepeterson-bestbuy** [GoogleCloudPlatform/k8s-config-connector#624] opened 2022-03-07 18:30 UTC
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

When deploying a BigTable GCPolicy resource, and specifying a maxAge duration of "90d", the resource fails with the following error: 
`Warning  UpdateFailed        11s (x5 over 5m47s)   bigtablegcpolicy-controller  Update call failed: error calculating diff: time: unknown unit "d" in duration "90d"`

However, all other units including ms, s, m, h, appear to work just fine.

### Kubernetes Cluster Version

Client Version: v1.19.4
Server Version: v1.20.10-gke.1600

### Config Connector Version

1.70.0

### Config Connector Mode

namespaced

**Comment by xiaobaitusi** [comment] 2022-03-10 20:06
Hi @joepeterson-bestbuy, I think that the root cause is that the underlying terraform [resource](https://github.com/hashicorp/terraform-provider-google-beta/blob/861b36bccf8e1bdf56065b6571c4bf7cc45ecb94/google-beta/resource_bigtable_gc_policy.go#L330) uses the time.ParseDuration() which doesn't support `d` time unit.

I would suggest to use `h` instead to unblock yourself now. If you really like to support `d`, do you mind creating an issue in https://github.com/hashicorp/terraform-provider-google-beta to surface the feature request?

**Comment by kevinsi4508** [comment] 2022-10-25 12:38
This should be resolved by using [`gc_rules`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_gc_policy#gc_rules). Currently we are waiting for KCC to update to the latest Google Provider version.

**Comment by mbzomowski** [comment] 2022-11-17 21:12
`spec.gcRules` has been added to `BigTableGCPolicy` as of Config Connector [v1.97.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.97.0). We don't recommend using `maxAge`, `maxVersion` or `mode` for defining a
BigTableGCPolicy as these fields have known drift detection issues. Instead, please use `gcRules`

**Closed by mbzomowski** 2022-11-17 21:12 UTC
Labels: bug
