### ISSUE TITLE
GCP resource name customisation

### ISSUE THREAD

**Issue by nrobert13** [GoogleCloudPlatform/k8s-config-connector#54] opened 2019-10-21 09:27 UTC
currently the KCC resource name is used to name the GCP resources, which introduces the [k8s naming constraints](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/). Would be nice to be able to use for ex capital letters in GCP resource names like cloudsql database.

**Comment by xiaobaitusi** [comment] 2019-10-21 20:19
Hi Robert, we have this feature planned for the future release. The initial thought is to have a separate field 'resourceName' in spec or lift it to directives annotation; if it's specified, KCC would use it instead of 'meta.name' for the underlying GCP resources. Let us know what you think of the initial approach.

**Comment by nrobert13** [comment] 2019-10-22 06:43
Hi Zeya, either of the solution would fit, I think I like the `resourceName` in spec more. In case naming constraints apply to the underlying API, you can enforce it with openapi validation...
thanks.

**Comment by maqiuyujoyce** [comment] 2019-10-23 22:57
@nrobert13 Thank you for your feedback! Will let you know when the feature is ready.

**Comment by lawrencejones** [comment] 2020-06-17 17:09
Hey team! We're really keen on being able to customise the resource names. The current model means restrictions on our Kubernetes structure bleed into the GCP project, which might not be ideal.

Is there any update on this functionality? Thanks.

**Comment by AlexBulankou** [comment] 2020-06-23 01:13
@lawrencejones , thanks for following up. This is planned for 2020 and in the next 3 months we'll have another update with a more specific ETA.

**Comment by n1koo** [comment] 2020-10-28 14:45
We are also interested in this. Any update?

**Comment by kibbles-n-bytes** [comment] 2020-10-28 14:56
Hey @n1koo , work is in progress for this with an ETA at the end of November.

**Comment by toumorokoshi** [comment] 2020-11-25 21:48
closing as a duplicate of #25, since it was the first request.

**Closed by toumorokoshi** 2020-11-25 21:48 UTC
Labels: enhancement
