### ISSUE TITLE
serviceusage requires cloudresourcemanager API enabled?

### ISSUE THREAD

**Issue by AlexBulankou** [GoogleCloudPlatform/k8s-config-connector#135] opened 2020-04-10 16:42 UTC
I am trying to enable `sqladmin.googleapis.com` on my project:
```
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/disable-dependent-services: "false"
  name: sqladmin.googleapis.com
```
However I get error from service-controller: 

```
Update call failed: error fetching live state: error reading underlying resource: Error reading Project Service XXX/sqladmin.googleapis.com: Batch "project/XXX/services" for request "List Project Services XXX" returned error: googleapi: Error 403: Cloud Resource Manager API has not been used in project XXX  before or it is disabled. 
```
When I'm trying to enable cloudresourcemanager API using serviceusage declaratively, I get the same error. Does it mean that cloudresourcemanager API needs to be enabled on the project using gcloud before I can use servicesage?

**Comment by xiaobaitusi** [comment] 2020-04-13 19:06
Confirmed that cloudresourcemanager API needs to be enabled on the project using gcloud or Google Cloud Console before using serviceusage kind.
Here is a similar issue on Terraform per https://github.com/terraform-providers/terraform-provider-google/issues/6101

**Comment by toumorokoshi** [comment] 2020-11-25 22:38
Closing this issue since the question was answered. if there is a desired additional step, please file a new issue as a bug / enhancement.

**Closed by toumorokoshi** 2020-11-25 22:38 UTC
Labels: question
