### ISSUE TITLE
Support resource names overrides outside of K8s allowed character range

### ISSUE THREAD

**Issue by reubenvanammers** [GoogleCloudPlatform/k8s-config-connector#128] opened 2020-03-31 04:25 UTC
Currently, as kubernetes only allows dashes in the name, not underscores, and Bigquery table names only allow underscores, not dashes,  it is impossible to use a separator (underscore/dash/space etc) when creating a table.
 
An obvious fix would be to convert all dashes to underscores when creating a table.

**Comment by maqiuyujoyce** [comment] 2020-03-31 19:09
@reubenvanammers Thank you for your feedback. We will look into being able to specify the resource ID in the spec and will let you know when we have more information.

**Comment by AlexBulankou** [comment] 2020-05-22 12:41
K8s limits character set to [a-z0-9]([-a-z0-9]*[a-z0-9])?

**Comment by max-sixty** [comment] 2020-05-27 03:57
Here's an example:

```
bigquerydataset.bigquery.cnrm.cloud.google.com/x unchanged

The BigQueryDataset "x_y" is invalid: metadata.name: Invalid value: "x_y": a 
DNS-1123 subdomain must consist of lower case alphanumeric characters, 
'-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', 
regex used for validation is 
'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
 
Is there any workaround?

Tangentially related: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/112

**Comment by maqiuyujoyce** [comment] 2020-05-30 02:37
@max-sixty thank you for the additional details. Unfortunately, "-" or "_" can't be used in the BigQuery table or dataset names in KCC right now. We are looking into supporting the feature to specify the resource ID in the spec, and with that feature, users can specify BigQuery resource names with "_" in it. Will keep you updated if we have more information.

**Comment by kibbles-n-bytes** [comment] 2020-05-30 17:16
@AlexBulankou From https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names :

> Most resource types require a name that can be used as a DNS subdomain name as defined in RFC 1123. This means the name must:
> - contain no more than 253 characters
> - contain only lowercase alphanumeric characters, ‘-’ or ‘.’
> - start with an alphanumeric character
> - end with an alphanumeric character

**Comment by RoryShively** [comment] 2020-09-24 14:55
Is there a timeline on this? I was told it would be worked on during Q3

**Comment by maqiuyujoyce** [comment] 2020-09-24 18:11
Hi @RoryShively , we're currently working on supporting resource name overrides and should have the feature out around the end of October.

**Comment by flunderpero** [comment] 2020-11-22 16:15
I am having the same issue with Storage bucket names and KMS keys (as a policy we use underscore everywhere if possible and only fall back to dash in Kubernetes) while trying to convert our configuration management to Cloud Configuration.

**Comment by toumorokoshi** [comment] 2020-11-25 22:44
closing as a duplicate of #25 (doing some light cleanup). Please watch that issue. 

As mentioned, we plan on providing a new field which isn't subject to k8s naming restrictions to specify the GCP resource name. The current ETA is by first week of January.

**Closed by toumorokoshi** 2020-11-25 22:44 UTC
Labels: enhancement
