### ISSUE TITLE
Cannot update permissions of a custom role

### ISSUE THREAD

**Issue by flunderpero** [GoogleCloudPlatform/k8s-config-connector#313] opened 2020-11-23 20:53 UTC
**Describe the bug**
When I try to update an existing role, I get this panic:
```
{ "controller": "iamcustomrole-controller", "msg": "Reconciler error", "request": "tkt-dev-pero/faas", "logger": "controller-runtime.controller", "error": "INTERNAL ERROR: panic: observed a panic: expected state's set to have value explicitly provided in spec
	/go/src/cnrm.googlesource.com/cnrm/pkg/execution/builtin.go:26 +0x57
	panic(0x33f67e0, 0xc000f068e0)
		/usr/local/go/src/runtime/panic.go:975 +0x3e3
	cnrm.googlesource.com/cnrm/pkg/krmtotf.convertTFSetToKCCSet(0x3192820, 0xc002b23040, 0x3192820, 0xc001f27ba0, 0xc000bc3400, 0xc0016e2c38, 0x3a150e3, 0xb, 0x51849a, 0xc0038430a8)
		/go/src/cnrm.googlesource.com/cnrm/pkg/krmtotf/tftokrm.go:502 +0xa82
	cnrm.googlesource.com/cnrm/pkg/krmtotf.convertTFMapToKCCMap(0xc0037db980, 0xc003516600, 0xc000bbe300, 0xc0016e2c38, 0x0, 0x0, 0xc001c3b4a0, 0x0)
		/go/src/cnrm.googlesource.com/cnrm/pkg/krmtotf/tftokrm.go:338 +0xa8c
	cnrm.googlesource.com/cnrm/pkg/krmtotf.ConvertTFObjToKCCObj(0xc0037db980, 0xc003516600, 0xc000bbe300, 0xc0016e2c38, 0x0, 0x0, 0xc001c3b4a0, 0xc002e30000)
		/go/src/cnrm.googlesource.com/cnrm/pkg/krmtotf/tftokrm.go:230 +0x7a
	cnrm.googlesource.com/cnrm/pkg/krmtotf.GetSpecAndStatusFromState(0xc0016e2b00, 0xc002eaad20, 0x0, 0x0)
		/go/src/cnrm.googlesource.com/cnrm/pkg/krmtotf/tftokrm.go:24 +0xcd
	cnrm.googlesource.com/cnrm/pkg/krmtotf.resolveUnmanagedFields(0xc0037daf60, 0xc0016e2b00, 0xc002eaad20, 0x0, 0x0, 0x100)
		/go/src/cnrm.googlesource.com/cnrm/pkg/krmtotf/krmtotf.go:145 +0xb6
	cnrm.googlesource.com/cnrm/pkg/krmtotf.krmResourceToTFResourceConfig(0xc0016e2b00, 0xc002eaad20, 0x41ca2c0, 0xc00022f540, 0xc000f4f640, 0x1, 0x0, 0xc002eaad20, 0x0, 0x0)
		/go/src/cnrm.googlesource.com/cnrm/pkg/krmtotf/krmtotf.go:57 +0x17d
	cnrm.googlesource.com/cnrm/pkg/krmtotf.KRMResourceToTFResourceConfigWithGCPManagedFields(...)
		/go/src/cnrm.googlesource.com/cnrm/pkg/krmtotf/krmtotf.go:46
	cnrm.googlesource.com/cnrm/pkg/controller/tf.(*Reconciler).sync(0xc00022f540, 0x41ae6c0, 0xc00005a1f8, 0xc0016e2b00, 0x41f2f00, 0x0, 0x0)
		/go/src/cnrm.googlesource.com/cnrm/pkg/controller/tf/controller.go:229 +0x546
	cnrm.googlesource.com/cnrm/pkg/controller/tf.(*Reconciler).Reconcile(0xc00022f540, 0xc001136ff0, 0xc, 0xc001136fd0, 0x4, 0x0, 0x0, 0x0, 0x0)
		/go/src/cnrm.googlesource.com/cnrm/pkg/controller/tf/controller.go:142 +0xbf3
	cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00194cb40, 0x350a1a0, 0xc001f44020, 0x137461723400)
		/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x161
	cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00194cb40, 0x137461723400)
		/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xae
	cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00194cb40)
		/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
	cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001f95e30)
		/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
	cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001f95e30, 0x41204c0, 0xc001fbef00, 0xc001fc4201, 0xc00087e300)
		/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
	cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001f95e30, 0x3b9aca00, 0x0, 0x1, 0xc00087e300)
		/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
	cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc001f95e30, 0x3b9aca00, 0xc00087e300)
		/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
	created by cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
		/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x305
	" }
```

Der CRNM-Service-Account has the owner role in our organization. 

I don't get the panic if I specify exactly the permissions that there are already set in the custom role. Removing a role works, too. But when I try to add one I don't see any event in the custom resource and get the panic in the logs.

**ConfigConnector Version**

1.27.1

**To Reproduce**
*Steps to reproduce the behavior:*

*YAML snippets:*

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
  name: myrole
spec:
  title: MYROLE
  description: Just some role
  permissions:
    - cloudkms.cryptoKeyVersions.useToDecrypt
    - cloudtrace.traces.patch
    - errorreporting.errorEvents.create
    - iam.serviceAccountKeys.get
    - iam.serviceAccounts.signJwt
    - pubsub.subscriptions.consume
    - pubsub.subscriptions.create
    - pubsub.subscriptions.get
    - pubsub.topics.attachSubscription
    - pubsub.topics.create
    - pubsub.topics.get
    - pubsub.topics.publish
    - spanner.instances.get
    - storage.buckets.get
    - storage.objects.create
    - storage.objects.delete
    - storage.objects.get
    - storage.objects.list
    - storage.objects.update
  stage: BETA
```

**Comment by xiaobaitusi** [comment] 2020-11-26 00:25
@flunderpero, this looks like a bug on our side, we'll work on fixing the issue soon and let you know when we have an update.

**Comment by tonybenchsci** [comment] 2020-12-11 05:11
@xiaobaitusi We're seeing this too on 
```
created by cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
		/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x305
	", "controller": "computeurlmap-controller" 
```
This is after annotate abandon, delete, and re-acquire process.

**Comment by toumorokoshi** [comment] 2020-12-11 19:55
Hi @tonybenchsci @flunderpero! We've fixed the underlying issue in the 1.33.0 release, which just shipped. Can you upgrade your version and see if it fixes your issue?

**Comment by tonybenchsci** [comment] 2020-12-21 14:26
@toumorokoshi I noticed on https://cloud.google.com/config-connector/docs/how-to/advanced-install#manual, that the manual instructions have changed from `gs://cnrm/` to `gs://configconnector-operator/latest/release-bundle.tar.gz`.

Is the old way still supported?

**Comment by toumorokoshi** [comment] 2020-12-21 22:59
> I've created Question #355 for this. 

Hi! It looks like discussion around that topic has started. I can chime in, but discussing in that issue sounds great.

**Comment by toumorokoshi** [comment] 2020-12-21 23:11
I'll close this issue for now since we have validated resolving this scenario on our side. feel free to re-open if you can reproduce this issue.

**Closed by toumorokoshi** 2020-12-21 23:11 UTC
Labels: bug

**Comment by eyalzek** [comment] 2020-12-22 13:40
Just hit this on v1.18.12-gke.300, a custom role was created by TF, then later a `IAMCustomRole` resource of the same name was created (and with an additional permission added to it). I'm seeing the exact same panic error as above on the `cnrm-controller-manager`.

**Comment by toumorokoshi** [comment] 2020-12-23 19:34
> Just hit this on v1.18.12-gke.300, a custom role was created by TF, then later a `IAMCustomRole` resource of the same name was created (and with an additional permission added to it). I'm seeing the exact same panic error as above on the `cnrm-controller-manager`.

Hi @eyalzek! Unfortunately it takes 3-4 weeks for the GKE add-on to be updated to the newest version.

We have some work slated in Q2 to improve the add-on turnaround speed. The workaround is a bit painful, but I believe if you hand-apply the permission first (through Terraform / cloud console) before applying the kcc resource, it'll resolve the reconciliation issue.
