### ISSUE TITLE
PubSubSubscription cannot create a subscription with no expiry

### ISSUE THREAD

**Issue by jsun6383** [GoogleCloudPlatform/k8s-config-connector#227] opened 2020-07-01 04:45 UTC
**Describe the bug**
I want to create a pubsub subscription with Config Connector that has no expiry.
As per documentation [here](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions#expirationpolicy) i should be able to do that if i do not set the `ttl` in the `expirationPolicy` object.

However, this does not work as the `ttl` field is marked as required by the Config Connector.

Also not specifying `expirationPolicy` at all will default the expiry of the subscription to 31 days.

**ConfigConnector Version**
1.7.2

**To Reproduce**

Creating the subscription with the manifest below results in an error as the `ttl` field is required as per the component [schema](https://cloud.google.com/config-connector/docs/reference/resource-docs/pubsub/pubsubsubscription).

```yaml
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: test-topic
  namespace: gcp

---

apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: test-subscription
  namespace: gcp
spec:
  expirationPolicy: {}
  topicRef:
    name: test-topic
    namespace: gcp
```

**Comment by xiaobaitusi** [comment] 2020-07-01 21:20
Hi @jsun6383, you can specify the `ttl` field with an empty string "" for no expiry. The behaviour is documented in the CRD [field description]( https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/crds/pubsub_v1beta1_pubsubsubscription.yaml#L130)

```yaml
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: test-subscription
  namespace: gcp
spec:
  expirationPolicy: 
    ttl: ""
  topicRef:
    name: test-topic
    namespace: gcp
```

**Comment by jsun6383** [comment] 2020-07-02 06:06
Thanks @xiaobaitusi. That worked.

Just a side note, this seem a little conflicting to the google documentation as it specifies ttl to not be set instead of setting it to "".

Also the same in Deployment Manager is actually `expirationPolicy: {}`

**Comment by maqiuyujoyce** [comment] 2020-07-07 21:46
Hi @jsun6383 , thank you for the additional information! We'll look into it.

**Comment by toumorokoshi** [comment] 2020-11-25 22:55
closing as the issue is resolved, but we will continue to investigate and see if the we can improve the UX, or at least make it consistent with deploymentManager.

**Closed by toumorokoshi** 2020-11-25 22:55 UTC
Labels: bug
