### ISSUE TITLE
Wordpress sample app issue

### ISSUE THREAD

**Issue by MingyanZhao** [GoogleCloudPlatform/k8s-config-connector#114] opened 2020-03-10 21:38 UTC
Hi,

I am trying to deploy the wordpress app. I have been following the instruction and fix a minor issue till `helm install`. The `helm install ....` does not throw any error but the Sqlinstance seems keep updating itself and the wordpress-external IP address seems not working. There is also no error or failure reported on my cluster or workload in my GCP project. Could someone please help?

Here is the result of `kubectl describe sqlinstance wp-db-1` (my instance name is `wp-db-1`):

```
Name:         wp-db-1
Namespace:    default
Labels:       cnrm-lease-expiration=1583877792
              cnrm-lease-holder-id=bpjuussinp3kb6fi4sa0
Annotations:  cnrm.cloud.google.com/management-conflict-prevention-policy: resource
              cnrm.cloud.google.com/project-id: myzh-subproject
API Version:  sql.cnrm.cloud.google.com/v1beta1
Kind:         SQLInstance
Metadata:
  Creation Timestamp:  2020-03-10T20:58:58Z
  Finalizers:
    cnrm.cloud.google.com/finalizer
  Generation:        5
  Resource Version:  1794169
  Self Link:         /apis/sql.cnrm.cloud.google.com/v1beta1/namespaces/default/sqlinstances/wp-db-1
  UID:               f60b5ffa-6311-11ea-a81d-42010a8a006c
Spec:
  Database Version:  MYSQL_5_7
  Region:            us-central1
  Settings:
    Activation Policy:  ALWAYS
    Backup Configuration:
      Start Time:     10:00
    Disk Autoresize:  true
    Disk Size:        10
    Disk Type:        PD_SSD
    Ip Configuration:
      ipv4Enabled:  true
    Location Preference:
      Zone:            us-central1-c
    Pricing Plan:      PER_USE
    Replication Type:  SYNCHRONOUS
    Tier:              db-f1-micro
Status:
  Conditions:
    Last Transition Time:  2020-03-10T21:23:48Z
    Message:               The resource is up to date
    Reason:                UpToDate
    Status:                True
    Type:                  Ready
  Connection Name:         myzh-subproject:us-central1:wp-db-1
  First Ip Address:        35.232.209.201
  Ip Address:
    Ip Address:       35.232.209.201
    Type:             PRIMARY
  Public Ip Address:  35.232.209.201
  Self Link:          https://www.googleapis.com/sql/v1beta4/projects/myzh-subproject/instances/wp-db-1
  Server Ca Cert:
    Cert:  -----BEGIN CERTIFICATE-----
MIIDfzCC...(omitting certificate content)....
-----END CERTIFICATE-----
    Common Name:                  C=US,O=Google\, Inc,CN=Google Cloud SQL Server CA,dnQualifier=d6d8d055-928e-4f9d-bc5d-e19830b28160
    Create Time:                  2020-03-10T20:58:59.583Z
    Expiration Time:              2030-03-08T20:59:59.583Z
    sha1Fingerprint:              2d0ff68ceeff3360426ae7d3392e6e4c168b400b
  Service Account Email Address:  p844351009096-n3iwws@gcp-sa-cloud-sql.iam.gserviceaccount.com
Events:
  Type    Reason    Age                  From                    Message
  ----    ------    ----                 ----                    -------
  Normal  Updating  6m43s (x2 over 30m)  sqlinstance-controller  Update in progress
  Normal  UpToDate  6m7s (x2 over 26m)   sqlinstance-controller  The resource is up to date
```

**Comment by MingyanZhao** [comment] 2020-03-11 01:17
Found an error

```
create Pod wordpress-0 in StatefulSet wordpress failed error: pods "wordpress-0" is forbidden: error looking up service account default/sql-wp-ksa-wi: serviceaccount "sql-wp-ksa-wi" not found
```

Will come back when fix the issue.

**Comment by spew** [comment] 2020-03-11 17:27
Hi @MingyanZhao do you know if the issue is a problem with the sample or an error on your side?

**Comment by MingyanZhao** [comment] 2020-03-11 19:41
Hi @spew ,

Thanks for the reply!

I fixed some of my mistake but I do think this is something wrong with the sample. 

Here is my update: The `cloudsql-proxy` is getting `CrashLoopBackOff` and I am looking for correct configuration for the service account.

```
2020/03/11 19:18:47 no service account found for this Compute Engine VM. Please create a new VM with Cloud SQL access (scope) enabled under "Identity and API access". Alternatively, create a new "service account key" and specify it using the -credential_file parameter
```

**Comment by toumorokoshi** [comment] 2020-11-25 21:26
Hi! It sounds like this is referring to the wordpress sample now found in [cloud-foundation-toolkit](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/config-connector/solutions/apps/helm/wordpress). I've ran through it and I was unable to repro (things worked ok).

I'm going to close this issue in this ticket, but if you are continuing to encounter errors, please file an issue in cloud-foundation-toolkit.

**Closed by toumorokoshi** 2020-11-25 21:26 UTC
