### ISSUE TITLE
admission webhook Denied the request

### ISSUE THREAD

**Issue by erolco** [GoogleCloudPlatform/k8s-config-connector#439] opened 2021-03-30 13:08 UTC
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

 I want to deploy kubeflow on privateGKE but I got admission webhook denied when I make apply.

### Kubernetes Cluster Version

Client Version: v1.20.4
Server Version: v1.18.15-gke.1501

### Config Connector Version

1.29.0

### Config Connector Mode

cluster

## Log Output

Error from server: error when creating ".build/gcp_config/container.cnrm.cloud.google.com_v1beta1_containercluster_kubecluster.yaml": admission webhook "deny-unknown-fields.cnrm.clou
d.google.com" denied the request: unknown field "spec.ipAllocationPolicy.createSubnetwork"
make: *** [Makefile:201: apply-gcp] Error 1

## Steps to Reproduce

I am following this document(https://master.kubeflow.org/docs/distributions/gke/private-clusters/)

### YAML snippets

apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: kubecluster
  namespace: erol-sandbox
  clusterName: erol-sandbox/europe-west1-b/kubecluster
  labels:
    kf-name: kubecluster
    mesh_id: proj-438623113090
spec:
  clusterAutoscaling:
    autoProvisioningDefaults:
      oauthScopes:
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring
      - https://www.googleapis.com/auth/devstorage.read_only
      serviceAccountRef:
        name: kubecluster-vm
    enabled: true
    resourceLimits:
    - maximum: 128
      resourceType: cpu
    - maximum: 2000
      resourceType: memory
    - maximum: 16
      resourceType: nvidia-tesla-k80
  initialNodeCount: 2
  ipAllocationPolicy:
    clusterSecondaryRangeName: pods
    createSubnetwork: false
    servicesSecondaryRangeName: services
    useIpAliases: true
  location: europe-west1-b
  loggingService: logging.googleapis.com/kubernetes
  monitoringService: monitoring.googleapis.com/kubernetes
  networkRef:
    name: kubecluster
  nodeConfig:
    metadata:
      disable-legacy-endpoints: "true"
    machineType: n1-standard-8
    oauthScopes:
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring
    - https://www.googleapis.com/auth/devstorage.read_only
    serviceAccountRef:
      name: kubecluster-vm
    workloadMetadataConfig:
      nodeMetadata: GKE_METADATA_SERVER
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: true
    masterIpv4CidrBlock: 172.16.0.32/28
  releaseChannel:
    channel: REGULAR
  subnetworkRef:
    name: kubecluster
  workloadIdentityConfig:
    identityNamespace: erol-sandbox.svc.id.goog

**Comment by caieo** [comment] 2021-04-01 15:58
Hi @erolco, we're sorry you ran into this issue. However, it looks like this is an expected behavior for our admission webhook because our Custom Resource Definition for ContainerCluster does not support the `spec.ipAllocationPolicy.createSubnetwork` field ([documentation on the CRD's spec here](https://cloud.google.com/config-connector/docs/reference/resource-docs/container/containercluster#spec)). I couldn't verify if the YAML you created was from the kubeflow documentation you posted, but I would recommend trying out the [samples that we have provided in this repository](https://github.com/GoogleCloudPlatform/k8s-config-connector/tree/master/samples/resources/containercluster) because we can ensure that they work.

**Comment by erolco** [comment] 2021-04-02 07:48
Hi @caieo , this yaml cretated automatically when deploy the kubeflow 1.2 and config connector. These yaml is immutable , i can't modify it.

**Comment by caieo** [comment] 2021-04-05 08:54
@erolco, I took a look at the issues brought up in the kubeflow documentation/tutorial you linked, and it looks like one of the previously opened issues (https://github.com/kubeflow/gcp-blueprints/issues/32#issuecomment-742254206) mentioned a similar error that you ran into regarding the `spec.ipAllocationPolicy.createSubnetwork` being invalid. Because we can only vouch for the validity of our own CRDs in this repository (which does not contain the `createSubnetwork` field), I can't verify if Kubeflow's configurations are up-to-date or working. However, I noticed (in that same issue thread) that the Kubeflow team merged a fix around mid-February to address this invalid field (https://github.com/kubeflow/manifests/issues/1745), which might help your case. I'm sorry I can't help with the Kubeflow documentation/confusion, and please let us know if (after re-attempting the fix with Kubeflow) this is actually an issue on our side.

**Comment by erolco** [comment] 2021-04-06 11:25
@caieo, thank you so much for your help, as you say, KCC does not support some field and I removed the createSubnetwork and useIpAliases fields from the yaml. But now i am getting different error.

 Wait for all Google Cloud resources to get created and become ready.
Waiting for iamserviceaccount resources...
error: no matching resources found
Error: waiting for iamserviceaccount ready timed out.
To troubleshoot, you can run:
kubectl --context=mymngt describe iamserviceaccount -l kf-name=kubecluster
make: *** [Makefile:340: wait-gcp] Error 1


$ kubectl --context=mymngt describe iamserviceaccount -l kf-name=kubecluster
No resources found in cnrm-system namespace.

**Comment by caieo** [comment] 2021-04-09 00:18
@erolco, sorry to see this happen. Unfortunately, this looks like a Kubeflow issue and doesn't seem to be bug with KCC. Unless there is a specific erroneous behavior with KCC that you can point me to, please forward your questions to the [Kubeflow repository](https://github.com/kubeflow/kubeflow/issues) for further assistance with your new error.

**Comment by erolco** [comment] 2021-04-09 12:36
@caieo  Thank you so much , I will forward it to Kubeflow repository.

**Comment by maqiuyujoyce** [comment] 2021-04-09 18:42
Closing as the original question has been answered. Please feel free to open new issues if you need any further help.

**Closed by maqiuyujoyce** 2021-04-09 18:42 UTC
Labels: bug
