### ISSUE TITLE
Deletion of folder (with deletion-policy: abandon) does not work if not empty

### ISSUE THREAD

**Issue by Scorpiion** [GoogleCloudPlatform/k8s-config-connector#145] opened 2020-04-16 11:30 UTC
**Describe the bug**
I tried to delete a folder only from KCC but not the underlying folder, it did not work. The folder did have projects inside.

**ConfigConnector Version**
```bash 
1.7.1
```

**To Reproduce**
*Steps to reproduce the behavior:*

*YAML snippets:*
```yaml
# Top level namespace used for folders
apiVersion: v1
kind: Namespace
metadata:
  name: global-resources
  annotations:
    cnrm.cloud.google.com/folder-id: "xxxxxx" # Folder where subfolders are created
    cnrm.cloud.google.com/project-id: xxxxxxxxxxx # Project id of project where the config connector is running

---

apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  namespace: global-resources
  name: xxxxxxxxxxxxxxxxx
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon # Don't delete GCP resource if KCC entry is deleted
spec:
  displayName: xxxxxxxxxxxxxxxxx

```
I got this error message:
```
status:
  conditions:
  - lastTransitionTime: "2020-04-16T11:20:33Z"
    message: 'Delete call failed: error deleting resource: Error deleting folder ''xxxxxxxxxxxx'':
      googleapi: Error 400: Precondition check failed., failedPrecondition'
    reason: DeleteFailed
    status: "False"
    type: Ready
  createTime: "2020-04-15T22:45:07.790Z"
  lifecycleState: ACTIVE
  name: folders/xxxxxxxxxxxx
```

I would have expected that I could delete the folder from KCC only because of the `cnrm.cloud.google.com/deletion-policy: abandon` annotation. The folder does have projects inside it, so if the folder would have actually been deleted it's correct, but in this case I'm just uninstalling YAML files so I can reinstall the KCC cluster.

**Comment by Scorpiion** [comment] 2020-04-16 11:32
If someone else runs into this, a manual way to "fix this" is to edit the definition like this:
```
kubectl edit folders.resourcemanager.cnrm.cloud.google.com --namespace global-resources xxxxxxxx
```

Then remove the row with `- cnrm.cloud.google.com/finalizer` and save
```
  finalizers:
  - cnrm.cloud.google.com/finalizer
```

The the folder is removed from your KCC install (and it remains in in GCP).

**Comment by jcanseco** [comment] 2020-04-16 19:39
Hi @Scorpiion, are you able to reproduce this consistently? We've been unable to reproduce the described scenario thus far.

**Comment by jcanseco** [comment] 2020-04-16 23:02
If you still have the controller logs from around the time you first deleted the resource, then those would help too. You can retrieve the logs using `kubectl logs cnrm-controller-manager-0 --namespace=cnrm-system`.

**Comment by kibbles-n-bytes** [comment] 2020-04-27 14:13
Hey @Scorpiion , going to close this out as we've attempted multiple times with your YAML and have not been able to reproduce this. Please make sure it wasn't one of the following:
- A misspelling on the annotation; one I've seen is `crnm` instead of `cnrm`
- The abandon annotation being added after the resource was already marked for deletion.

If you're able to reproduce this behavior and can give us the exact state in etcd and logs, feel free to open another issue. If there is any artifacts you'd rather not post on GitHub, you can go through Google Cloud support.

**Closed by kibbles-n-bytes** 2020-04-27 14:13 UTC
Labels: bug

**Comment by Scorpiion** [comment] 2020-06-03 12:16
Hi guys, thanks for your responses and sorry for my late one. I have not had time to reproduce and test this more. I will let you know if I run into this again or not, hopefully I won't.
