### ISSUE TITLE
reference sql user password from secret manager 

### ISSUE THREAD

**Issue by ni-ezakaria** [GoogleCloudPlatform/k8s-config-connector#297] opened 2020-11-03 03:08 UTC
Is there a way to reference a secret manager secret as an sql user password ? 
that will be really helpful , to avoid creating a k8s secret 
thanks in advance

**Comment by jcanseco** [comment] 2020-11-10 01:32
Hi @ni-ezakaria, we currently don't have support for such a feature, but it is an idea that has come up before. I'll leave this issue open and mark it as an enhancement so that we can track this issue as a feature request.

Could you please elaborate on whether you consider this feature request a blocker, pain point, or nice-to-have?

Also, one thing to note is that if you're already using Config Connector to manage secret manager secrets, you could share the same K8s Secrets you reference in your `SecretManagerSecretVersion` resources with your `SQLUser` resources. I'm not sure if such a strategy would be sufficient for your use-case, but it's just an idea that I thought I'd throw out there.

**Comment by jcanseco** [comment] 2020-11-10 01:34
Also linking this issue to another related issue: Issue #272

**Comment by ni-ezakaria** [comment] 2020-11-12 18:49
hi @jcanseco  .. thanks for your feedback  , i wold say it's a pain point ... however this approach of having the SecretManagerSecret automatically create a K8s Secret that can be referenced from other resources  will do the trick.

**Comment by jcanseco** [comment] 2020-11-12 19:44
Gotcha, thanks for clarifying @ni-ezakaria.

**Comment by toumorokoshi** [comment] 2021-01-25 17:18
Hi! Closing this issue as a duplicate of #272. We'll be able to see this issue as an additional use case that should be satisfied by the final solution.

Thanks for raising the issue.

**Closed by toumorokoshi** 2021-01-25 17:18 UTC
Labels: enhancement
