### ISSUE TITLE
Updating resource_labels field on google_container_cluster fails with a 400 error

### ISSUE THREAD

**Issue by tonybenchsci** [GoogleCloudPlatform/k8s-config-connector#117] opened 2020-03-11 19:23 UTC
Exact same issue as this:
https://github.com/terraform-providers/terraform-provider-google/issues/5608

However this is worse on KCC because:
1. Since kcc version 1.4.0, there're now 3 cnrm labels. So most resources will want to update labels
2. Any nodepools that depend on the cluster updating labels will show resourceRef not ready.

**Comment by Scorpiion** [comment] 2020-03-11 20:07
Note to maintainers, please see discussion here (very similar or the same issue basically) https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/110

**Comment by spew** [comment] 2020-03-16 15:13
Hello @tonybenchsci, thanks for reporting this issue. It appears to be a duplicate of #110, please reopen if you feel this is not true.

**Closed by spew** 2020-03-16 15:13 UTC
Labels: bug
