### ISSUE TITLE
BigtableInstance deletionProtection

### ISSUE THREAD

**Issue by npitts0811** [GoogleCloudPlatform/k8s-config-connector#569] opened 2021-11-03 14:47 UTC
When reviewing the BigtableInstance CRD, the schema calls out a boolean for deletionProtection, however there is no documentation on what this is supposed to do or how it works. I have tried setting it to 'true', but the instance is still deleted. I have also checked the Bigtable Instance API documentation, but it doesn't look like deletionProtection is part of the API (so it must be specific to KCC). Could someone please elaborate on the behavior of this attribute? Docs for BigtableInstance CRD and API are linked below. Thanks!

* BigtableInstance CRD: https://cloud.google.com/config-connector/docs/reference/resource-docs/bigtable/bigtableinstance
* BigtableInstance API: https://cloud.google.com/bigtable/docs/reference/admin/rest/v2/projects.instances

**Comment by jcanseco** [comment] 2021-11-03 17:28
Apologies @nathanielpitts-bestbuy, this is a mistake on our part. The `deletionProtection` field is supposed to have been deprecated, but the field's description has not been updated to say so for some reason (there is probably a bug in the description generation logic somewhere).

We'll put out a fix ASAP to prevent further confusion.

**Comment by jcanseco** [comment] 2021-11-03 18:03
I've identified the root cause and should have a fix out in the next 1-2 releases.

**Comment by nathanielpitts-bestbuy** [comment] 2021-11-04 16:09
@jcanseco Makes sense, thanks for the clarification!

**Comment by kevinsi4508** [comment] 2022-10-25 12:53
Can we close this question?

**Comment by jcanseco** [comment] 2022-10-25 21:02
Yep.

**Closed by jcanseco** 2022-10-25 21:02 UTC
Labels: question
