### ISSUE TITLE
Unable to remove LifecycleRule from GCS Resources again

### ISSUE THREAD

**Issue by erik-carlson** [GoogleCloudPlatform/k8s-config-connector#595] opened 2022-01-20 17:52 UTC
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

Per #554 we have been setting lifecycleRule to an empty list to remove lifecycle rules (and actually on all buckets with no lifecycle policy defined), which worked on config connector version 1.60.0.  However, we recently noticed (on config connector version 1.69.0) that config connector fails with that configuration with "StorageBucket: cannot interpret non-list <nil> as list".  In #554 it looks like kishorv06 had the same issue on config connector version 1.63.0

### Kubernetes Cluster Version

Client Version: 1.20.8-dispatcher
Server Version: 1.20.10-gke.1600

### Config Connector Version

1.69.0

### Config Connector Mode

namespaced

## Log Output

StorageBucket: cannot interpret non-list <nil> as list

### Steps to reproduce the issue
Create a storgebucket resource with a lifecycleRule set to an empty list: []

**Comment by jcanseco** [comment] 2022-01-20 21:02
@erik-carlson thanks for bringing this issue up. We missed the latest comment on that other issue that mentioned this problem.

Yes I can confirm that I am able to reproduce the same error. It seems the issue started in KCC v1.61.0. Let me take some time to further investigate and see what happened.

**Comment by jcanseco** [comment] 2022-01-24 19:42
We've managed to narrow down the problem to a particular commit. It seems the problem was introduced due to an upgrade to one our dependencies, so it might take some time to understand what's going on. That's what we have so far -- we'll post updates accordingly.

**Comment by jcanseco** [comment] 2022-04-07 00:17
Hi folks, apologies for long delay. We've root-caused the issue and will put out a fix soon (next 1-2 releases).

**Comment by maqiuyujoyce** [comment] 2022-04-13 21:05
The fix is released in v1.81.0.

**Closed by maqiuyujoyce** 2022-04-13 21:05 UTC
Labels: bug
