### ISSUE TITLE
KCC - Project Activity Logging?

### ISSUE THREAD

**Issue by travisrandolph-bestbuy** [GoogleCloudPlatform/k8s-config-connector#412] opened 2021-03-01 22:46 UTC
We've noticed lately that projects deployed via KCC have a large amount of activities in the Project activity log. This isn't just for new resources, but specifically for updates or patching. For example every 5 minutes we get a project update activity. Also for firewalls rules there are patching activities every 10 minutes. Is there a way to suppress that activity as it's making it harder to see actual changes to the project/resources? Also could you give us some information on what is changing for the given resources?

**Comment by maqiuyujoyce** [comment] 2021-03-04 01:41
Hi @travisrandolph-bestbuy , thanks for reporting the issue. To better understand your problem, could you clarify the following questions?

1.  > projects deployed via KCC have a large amount of activities in the Project activity log

    1. I assume the `Project activity log` means the logs under https://console.cloud.google.com/logs for a particular project?
    2. Did you find the logs under the projects that were created by Config Connector (but not the one with Config Connector installed), right?

2. > This isn't just for new resources, but specifically for updates or patching. For example every 5 minutes we get a project update activity.

    1. Could you share the log content if possible? With detailed log info, we can better understand what has happened. I created a project via Config Connector but didn't see any new activity logged every 5 minutes. Though it does log an UpdateProject activity every 20m. This is because [Config Connector refreshes the label for the lease every 20 minutes](https://cloud.google.com/config-connector/docs/concepts/managing-conflicts).
    2. Also, it would be great if you can share information to reproduce your issue. Could you provide information including:
        1. Config Connector version (by running `kubectl get ns cnrm-system -o jsonpath='{.metadata.annotations.cnrm\.cloud\.google\.com/version}'`) and other useful information about your installation of Config Connector.
        2. Steps to reproduce the issue.
        3. YAML snippet for the associated resource(s).

3.  > Also for firewalls rules there are patching activities every 10 minutes.

    1. Similarly, I created a ComputeFirewall resource via Config Connector but didn't see any activity associated with firewall rule (`resource.type="gce_firewall_rule"`) other than the log for creation. Would be great if you can share the typical log content, and provide the information to reproduce the scenario.

**Comment by travisrandolph-bestbuy** [comment] 2021-03-04 15:39
@maqiuyujoyce Thanks for your response. I'm talking about the Activity tab on the homepage. I've added a screenshot for you. I've seen resources that don't print information to the Activity page, for example, updating a Custom Role. I did notice that the labels are updated for the CNRM lease config. So I was hoping maybe we could remove the Activity entries for the project updates. As for the firewall patch, is the insertID being changed? We are running 1.34.0. I can add yaml snippets if you require them, but I think this is more of a Log->Activity page configuration.

![image](https://user-images.githubusercontent.com/75803296/109981691-c24b0f80-7cc6-11eb-98f5-04547688c94f.png)

Log Entry - Project
```json
{
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "status": {},
    "authenticationInfo": {
      "principalEmail": "{{REDACTED}}.iam.gserviceaccount.com",
      "serviceAccountDelegationInfo": [
        {
          "principalSubject": "serviceAccount:{{REDACTED}}svc.id.goog[cnrm-system/cnrm-controller-manager-{{REDACTED}}-com]"
        }
      ]
    },
    "requestMetadata": {
      "callerIp": "gce-internal-ip",
      "callerSuppliedUserAgent": "google-api-go-client/0.5 Terraform/ (+https://www.terraform.io) Terraform-Plugin-SDK/2.1.0 terraform-provider-google-beta/dev,gzip(gfe)",
      "requestAttributes": {},
      "destinationAttributes": {}
    },
    "serviceName": "cloudresourcemanager.googleapis.com",
    "methodName": "UpdateProject",
    "authorizationInfo": [
      {
        "resource": "projects/{{REDACTED}}",
        "permission": "resourcemanager.projects.update",
        "granted": true,
        "resourceAttributes": {}
      }
    ],
    "resourceName": "projects/{{REDACTED}}",
    "request": {
      "@type": "type.googleapis.com/google.cloudresourcemanager.v1.UpdateProjectRequest",
      "projectId": "{{REDACTED}}",
      "project": {
        "createTime": "2020-12-08T13:40:39.642Z",
        "projectId": "{{REDACTED}}",
        "projectNumber": "{{REDACTED}}",
        "labels": {
          "cnrm-lease-holder-id": "bu7l52bf4ljcogkfub4g",
          "cnrm-lease-expiration": "1614868478",
          "managed-by-cnrm": "true",
        },
        "parent": {
          "id": "{{REDACTED}}",
          "type": "folder"
        },
        "lifecycleState": "ACTIVE",
        "name": "{{REDACTED}}"
      }
    },
    "response": {
      "createTime": "2020-12-08T13:40:39.642Z",
      "lifecycleState": "ACTIVE",
      "parent": {
        "type": "folder",
        "id": "{{REDACTED}}"
      },
      "projectNumber": "{{REDACTED}},
      "name": "{{REDACTED}}",
      "labels": {
        "cnrm-lease-expiration": "1614868478",
        "cnrm-lease-holder-id": "bu7l52bf4ljcogkfub4g",
        "managed-by-cnrm": "true",,
      },
      "projectId": "{{REDACTED}}",
      "@type": "type.googleapis.com/google.cloudresourcemanager.v1.Project"
    }
  },
  "insertId": "rhhrhqdomk6",
  "resource": {
    "type": "project",
    "labels": {
      "project_id": "{{REDACTED}}"
    }
  },
  "timestamp": "2021-03-04T13:54:38.656Z",
  "severity": "NOTICE",
  "logName": "projects/{{REDACTED}}/logs/cloudaudit.googleapis.com%2Factivity",
  "receiveTimestamp": "2021-03-04T13:54:39.210568469Z"
}
```

Log Entry - Firewall Patch
```json
{
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "authenticationInfo": {
      "principalEmail": "{{REDACTED}}.iam.gserviceaccount.com",
      "serviceAccountDelegationInfo": [
        {
          "principalSubject": "serviceAccount:{{REDACTED}}.svc.id.goog[cnrm-system/cnrm-controller-manager-{{REDACTED}}]"
        }
      ]
    },
    "requestMetadata": {
      "callerIp": "{{REDACTED}}",
      "callerSuppliedUserAgent": "Terraform/ (+https://www.terraform.io) Terraform-Plugin-SDK/2.1.0 terraform-provider-google-beta/dev,gzip(gfe)",
      "callerNetwork": "//compute.googleapis.com/projects/{{REDACTED}}/global/networks/__unknown__",
      "requestAttributes": {
        "time": "2021-03-04T14:13:53.050529Z",
        "auth": {}
      },
      "destinationAttributes": {}
    },
    "serviceName": "compute.googleapis.com",
    "methodName": "beta.compute.firewalls.patch",
    "authorizationInfo": [
      {
        "permission": "compute.firewalls.update",
        "granted": true,
        "resourceAttributes": {
          "service": "compute",
          "name": "projects/{{REDACTED}}/global/firewalls/dataflow-rule1",
          "type": "compute.firewalls"
        }
      },
      {
        "permission": "compute.networks.updatePolicy",
        "granted": true,
        "resourceAttributes": {
          "service": "compute",
          "name": "projects/{{REDACTED}}/global/networks/{{REDACTED}}",
          "type": "compute.networks"
        }
      }
    ],
    "resourceName": "projects/{{REDACTED}}/global/firewalls/dataflow-rule1",
    "request": {
      "logConfig": {
        "enable": true
      },
      "disabled": false,
      "alloweds": [
        {
          "IPProtocol": "tcp",
          "ports": [
            "12345-12346"
          ]
        }
      ],
      "network": "projects/{{REDACTED}}/global/networks/{{REDACTED}}",
      "sourceTags": [
        "dataflow"
      ],
      "@type": "type.googleapis.com/compute.firewalls.patch",
      "targetTags": [
        "dataflow"
      ],
      "priority": "1000",
      "description": "Allow internal dataflow communication"
    },
    "response": {
      "targetLink": "https://www.googleapis.com/compute/beta/projects/{{REDACTED}}/global/firewalls/dataflow-rule1",
      "insertTime": "2021-03-04T06:13:52.863-08:00",
      "id": "{{REDACTED}}",
      "selfLink": "https://www.googleapis.com/compute/beta/projects/{{REDACTED}}/global/operations/operation-{{REDACTED}}",
      "operationType": "patch",
      "@type": "type.googleapis.com/operation",
      "status": "RUNNING",
      "progress": "0",
      "selfLinkWithId": "https://www.googleapis.com/compute/beta/projects/{{REDACTED}}/global/operations/{{REDACTED}}",
      "user": "{{REDACTED}}.iam.gserviceaccount.com",
      "name": "operation-{{REDACTED}}",
      "startTime": "2021-03-04T06:13:52.871-08:00",
      "targetId": "{{REDACTED}}"
    },
    "resourceOriginalState": {
      "direction": "INGRESS",
      "creationTimestamp": "2020-12-08T05:57:01.749-08:00",
      "sourceTags": [
        "dataflow"
      ],
      "enableLogging": true,
      "description": "Allow internal dataflow communication",
      "selfLinkWithId": "https://www.googleapis.com/compute/beta/projects/{{REDACTED}}/global/firewalls/{{REDACTED}}",
      "name": "dataflow-rule1",
      "priority": "1000",
      "selfLink": "https://www.googleapis.com/compute/beta/projects/{{REDACTED}}global/firewalls/dataflow-rule1",
      "network": "https://www.googleapis.com/compute/beta/projects/{{REDACTED}}/global/networks/{{REDACTED}}",
      "id": "{{REDACTED}}",
      "alloweds": [
        {
          "IPProtocol": "tcp",
          "ports": [
            "12345-12346"
          ]
        }
      ],
      "targetTags": [
        "dataflow"
      ],
      "@type": "compute.googleapis.com/patch.state",
      "logConfig": {
        "enable": true
      },
      "disabled": false
    },
    "resourceLocation": {
      "currentLocations": [
        "global"
      ]
    }
  },
  "insertId": "{{REDACTED}}",
  "resource": {
    "type": "gce_firewall_rule",
    "labels": {
      "project_id": "{{REDACTED}}",
      "firewall_rule_id": "{{REDACTED}}"
    }
  },
  "timestamp": "2021-03-04T14:13:52.519917Z",
  "severity": "NOTICE",
  "logName": "projects/{{REDACTED}}/logs/cloudaudit.googleapis.com%2Factivity",
  "operation": {
    "id": "operation-1614867232473-5bcb693c04184-6f1f1e71-c9578160",
    "producer": "compute.googleapis.com",
    "first": true
  },
  "receiveTimestamp": "2021-03-04T14:13:53.135222885Z"
}
```

**Comment by maqiuyujoyce** [comment] 2021-03-05 04:46
Hi @travisrandolph-bestbuy , thank you for the detailed response. From the screenshot, it seems that both the Project and the ComputeFirewall have been updated every 10 mins. This made me suspect that those resources are changed regularly outside of Config Connector so that the drift detection is happening every 10 mins. Do you know if those resources happen to be managed by other toolings/pipelines?

>  I did notice that the labels are updated for the CNRM lease config. So I was hoping maybe we could remove the Activity entries for the project updates.

If the logs are really causing issues and you're okay with manually [managing the conflicts](https://cloud.google.com/config-connector/docs/concepts/managing-conflicts), then the workaround is to disable the leasing mechanism using annotation `cnrm.cloud.google.com/management-conflict-prevention-policy: "none"`.

**Comment by erik-carlson** [comment] 2021-11-05 17:37
I work with @travisrandolph-bestbuy and we're still seeing this behavior for computefirewall resources, though I don't see the logs for projects anymore.  We are not managing these same resources with other config connector clusters or other tools.  The other thing that we see related to this is that the computefirewall resources in kubernetes will go into an "updating" status (which also means that it isn't "ready") every 10 min.  Where every other resource has a status age that is more or less reflective of when the resource was created, computefirewalls never have a status age of over 10 min.

We're currently on version 1.60.0.

**Comment by jcanseco** [comment] 2021-11-05 22:17
> The other thing that we see related to this is that the computefirewall resources in kubernetes will go into an "updating" status (which also means that it isn't "ready") every 10 min.

This is probably the issue. Constant updating is almost always a symptom of an issue in Config Connector.

Can you share your `ComputeFirewall` YAML and the the resource's current state on K8s using `kubectl describe`?

**Comment by erik-carlson** [comment] 2021-11-06 14:35
here's an example of one.  The status was `Updating` right before I pulled the yaml, but switched to `UpToDate` as you can see below:
```
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {{REDACTED}}
    cnrm.cloud.google.com/state-into-spec: merge
    meta.helm.sh/release-name: {{REDACTED}}
    meta.helm.sh/release-namespace: {{REDACTED}}
  creationTimestamp: "2021-10-21T18:24:17Z"
  finalizers:
  - cnrm.cloud.google.com/finalizer
  - cnrm.cloud.google.com/deletion-defender
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  managedFields:
  - apiVersion: compute.cnrm.cloud.google.com/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
      f:spec:
        .: {}
        f:deny: {}
        f:description: {}
        f:destinationRanges: {}
        f:direction: {}
        f:enableLogging: {}
        f:networkRef:
          .: {}
          f:name: {}
        f:priority: {}
    manager: helm
    operation: Update
    time: "2021-10-21T18:24:17Z"
  - apiVersion: compute.cnrm.cloud.google.com/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"cnrm.cloud.google.com/deletion-defender": {}
          v:"cnrm.cloud.google.com/finalizer": {}
      f:spec:
        f:resourceID: {}
      f:status:
        .: {}
        f:conditions: {}
        f:creationTimestamp: {}
        f:observedGeneration: {}
        f:selfLink: {}
    manager: cnrm-controller-manager
    operation: Update
    time: "2021-10-21T18:33:40Z"
  name: default-deny-egress
  namespace: {{REDACTED}}
  resourceVersion: "47668001"
  uid: dc5775b0-a072-4eac-88e5-5fbbcf3e0bb0
spec:
  deny:
  - protocol: all
  description: Deny all egress traffic by default
  destinationRanges:
  - 0.0.0.0/0
  direction: EGRESS
  enableLogging: true
  networkRef:
    name: {{REDACTED}}
  priority: 801
  resourceID: default-deny-egress
status:
  conditions:
  - lastTransitionTime: "2021-11-06T14:17:08Z"
    message: The resource is up to date
    reason: UpToDate
    status: "True"
    type: Ready
  creationTimestamp: "2021-07-22T14:41:10.824-07:00"
  observedGeneration: 2
  selfLink: https://www.googleapis.com/compute/v1/projects/{{REDACTED}}/global/firewalls/default-deny-egress```

**Comment by jcanseco** [comment] 2021-11-08 20:05
Hi @erik-carlson, thank you. I was able to reproduce the issue.

It seems `ComputeFirewall` resources constantly update if `enableLogging` is specified. It seems the reason is because there is no logic in place to read back the value of `enableLogging` from the GCP API, hence KCC thinks there's always a diff since it thinks that the field "doesn't exist" in the underlying resource.

I created https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/570 to track this issue.

That said, it turns out that `enableLogging` is actually deprecated in favor of `logConfig`. If you use `logConfig` instead, then you won't have the constant updating issue. Given that this workaround exists and that `enableLogging` is meant to be deprecated in any case, we likely won't be prioritizing a fix to the issue any time soon. Instead, we recommend using `logConfig` instead.

Please let us know if that works for you.

**Comment by erik-carlson** [comment] 2021-11-08 20:14
Awesome, that should work.  Thanks!

**Comment by jcanseco** [comment] 2021-11-08 20:30
Awesome, thanks for confirming. In that case, I'll be closing this issue then. Please feel free to comment if you encounter the issue again.

**Closed by jcanseco** 2021-11-08 20:30 UTC
