### ISSUE TITLE
plans to support datastore?

### ISSUE THREAD

**Issue by nrobert13** [GoogleCloudPlatform/k8s-config-connector#50] opened 2019-10-17 13:19 UTC
would be nice to have

**Comment by xiaobaitusi** [comment] 2019-10-17 20:08
Hi, which resource are you referring to? We plan to cover all GCP resources eventually. Now we prioritize a selected list of resources based on beta customers feedback and requirements.

**Comment by nrobert13** [comment] 2019-10-21 08:38
I meant to create the firestore database either in native or in datastore mode.

**Comment by AlexBulankou** [comment] 2019-10-30 00:41
Dupe of https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/18

**Closed by AlexBulankou** 2019-10-30 00:41 UTC
Labels: duplicate
