### ISSUE TITLE
GCE metadata not defined for Service Account

### ISSUE THREAD

**Issue by PatrickGopher** [GoogleCloudPlatform/k8s-config-connector#273] opened 2020-09-11 07:22 UTC
**Describe the bug**
Error: 
error setting policy member: error fetching live state for resource: error reading underlying resource: Error when reading or editing Resource "project \"projects/storage-xxx\"" with IAM Member: Role "roles/dataflow.admin" Member "serviceAccount:my-component-12345-xxx@storage-xxx.iam.gserviceaccount.com": Error retrieving IAM policy for project "projects/storage-xxx": googleapi: Error 403: The caller does not have permission, forbidden"   

Error in events:
call failed: error fetching live state: error reading underlying resource: Error when reading or editing Service Account "projects/xpn-1/serviceAccounts/break-glass@xpn-1.iam.gserviceaccount.com": Get "https://iam.googleapis.com/v1/projects/xpn-1/serviceAccounts/break-glass@xpn-1.iam.gserviceaccount.com?alt=json&prettyPrint=false": metadata: GCE metadata "instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2FauthA%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fndev.clouddns.readwrite%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth.full_control%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.readonly" not defined

**ConfigConnector Version**
1.20.0

**To Reproduce**
The error continuously happens in our cluster. 

*YAML snippets:*

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: break-glass
  annotations:
    configmanagement.gke.io/cluster-selector: location-global
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: break-glass
  bindings:
  - role: roles/iam.serviceAccountTokenCreator
    members:
    - group:infra@iam.xxx.com

```

**Comment by kibbles-n-bytes** [comment] 2020-09-14 15:50
Hey @PatrickGopher , which installation method of Config Connector are you using? I was unable to reproduce on the workload identity installation. I believe we've seen this error come from GKE when the cluster's workload identity or metadata server configuration is misconfigured; could you share your cluster configuration?

**Comment by snuggie12** [comment] 2021-01-06 07:16
I have 1.19.0 and almost exact same problem with any `IAMPolicyMember`. It seems to work but the kubernetes resource status throws this error:

```
       error setting policy member: error fetching live state for resource:
        error reading underlying resource: Error when reading or editing
        Resource "project \"REDACTED\"" with IAM Member: Role
        "roles/dns.admin" Member
        "serviceAccount:acme-dns01-solver@REDACTED.iam.gserviceaccount.com":
        Error retrieving IAM policy for project "REDACTED":
        googleapi: Error 403: The caller does not have permission, forbidden
```

Can you clarify what part of workload identity might be broken? Happy to share.

**Comment by snuggie12** [comment] 2021-01-06 07:17
@PatrickGopher What do you mean by "error in events"?

**Comment by jcanseco** [comment] 2021-01-06 18:52
Hi @snuggie12, your error message looks more like the Google Service Account (GSA) used by KCC doesn't have sufficient permissions to manage IAM for the referenced resource (which I believe is a Project in this case). Can you please check that your KCC GSA has permissions to manage IAM for the referenced Project?

**Comment by snuggie12** [comment] 2021-01-06 21:59
@jcanseco the documentation [here](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#identity) says `owner` is required. The GSA has `DNS Administrator`, `Owner`, `Kubernetes Engine Admin`, and `Organization Administrator` applied at the org level.

That's why I was asking about where the GCE metadata log comes from. On GCP I'm looking at `resource.type="service_account"` on the project running GKE, but suspect there could be another place to look.

**Comment by jcanseco** [comment] 2021-01-07 00:58
Hi @snuggie12, gotcha, apologies. Are you also seeing the "GCE metadata [...] not defined" message? I believe what @PatrickGopher meant by "error in events" is that he saw that message in the resource's event log as seen when running `kubectl describe`. 

Unfortunately, I am not very familiar with the workload identity / metadata server malconfiguration issue that @kibbles-n-bytes mentioned and he's currently OOO, nor am I familiar with GCE metadata logs. Please allow me some time to investigate.

**Comment by jcanseco** [comment] 2021-01-07 01:05
Another thing: could you also try our [troubleshooting instructions](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#troubleshooting-permissions-for-resource-reconciliations); it tests workload identity in particular.

**Comment by snuggie12** [comment] 2021-01-07 01:33
@jcanseco Thanks for the quick replies. Discovered a few things:
- My mentioning of the GCP logs was a red herring (had to do with the fact we recently migrated clusters but the old cluster was still on.)
- If I delete the resource (both k8s and the real underlying resource) then status goes back to normal.
- If I add the abandon annotation and delete the resource it never gets a status.
- All other kcc resources I use aside from iampolicymember shows events if I `kubectl get events -n namespace`.
- The logs on the controller always show a start of reconiliation, then `cnrm-controller-manager-0 manager {"level":"info","ts":1609981997.5880456,"logger":"tfiamclient","msg":"underlying resource is already up to date","resource":{"namespace":"namespace","name":"foo"}}` and then it finishes.
- Tried the troubleshooting steps and everything works fine.

This leads me to believe that perhaps the logic for the iam controller isn't ensuring the k8s status is correct. Terraform believes nothing has changed on the GCP resource (because it hasn't and is working fine,) so no need to update the status. Instead it should see the underlying resource is fine and then check the status field to make sure status.conditions[0].status is "True" and if not then update status.

**Comment by snuggie12** [comment] 2021-01-07 02:17
I suspect the event issue I mentioned is somehow related to this. The other controllers look just like `service-controller` except for `registration-controller`, `iampolicy-controller`, and `iampolicymember-controller` (look towards the end with `Kind`):
```
{"level":"info","ts":1609985006.8112411,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"service-controller","source":"kind source: serviceusage.cnrm.cloud.google
.com/v1beta1, Kind=Service"}
{"level":"info","ts":1609985006.8112884,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"iampolicymember-controller","source":"kind source: /, Kind="}
```

**Comment by snuggie12** [comment] 2021-01-07 02:31
This might have been fixed in 1.34.0. Will upgrade and test but that might take a second as we previously had issues in the past with the operator and do a manual install.

**Comment by jcanseco** [comment] 2021-01-08 22:33
Hi @snuggie12, thanks for sharing with us your findings. We always greatly appreciate our customers' engagement with us.

A few questions/points:

> All other kcc resources I use aside from iampolicymember shows events if I kubectl get events -n namespace.

This is to be expected as `IAMPolicyMember` did not support events other than `UpToDate` prior to 1.34.0 (see [release notes](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/1.34.0) for list of new events), so it is normal not see any events for `IAMPolicyMember` if it never reached an `UpToDate` status.

> If I delete the resource (both k8s and the real underlying resource) then status goes back to normal.
> If I add the abandon annotation and delete the resource it never gets a status.

Could you please clarify these statements? 

When you say "k8s resource" and "underlying resource", are you referring to the `IAMPolicyMember` or the referenced project?

If you're referring to `IAMPolicyMember`, what do you mean by "status"? I'm assuming you don't mean the resource's `status` block as you wouldn't be able to see it once you delete the k8s resource, hence my confusion.

> This leads me to believe that perhaps the logic for the iam controller isn't ensuring the k8s status is correct.

I think this is a reasonable theory actually since we've had and fixed problems before where the status was not being updated correctly.

Have you been observing the same issue after updating to KCC 1.34.0?

**Comment by snuggie12** [comment] 2021-01-09 00:31
@jcanseco most importantly, the upgrade to `1.34.0` fixed our problems. Anything in this comment from here on out might be trivial since the suggestion to people having a problem should be "upgrade kcc".

>     Could you please clarify these statements?
> When you say "k8s resource" and "underlying resource", are you referring to the IAMPolicyMember, or are you referring to the referenced project?

When I said "k8s resource" I'm talking about some custom resource that kcc created and exists in etcd in kubernetes. "Underlying resource" refers to the GCP resource that gets created. So an underlying sql instance is the literal object in cloud sql where as the k8s resource is the kcc/cnrm representation of it in the k8s cluster. When I'm talking about status it is the literal path in a k8s resource of `.status`.

Hopefully that makes sense? What I'm trying to say is if you `kubectl delete sqlinstance` different things will happen depending on the existance of that annotation.

Post upgrade all of the `.status.conditions[0].status` of `IAMPolicyMember`s updated to `"True"`. At first I thought it was possible the upgrade was not related and was fixed by a simple restart of a `Pod`. However, one other random website like stackoverflow had recommended deleting my KSA and the pod and multiple attempts produced nothing.

Upgrading did fix the problem and also started producing kubernetes events (i.e. `kubectl get events`) for iam policy member resources.

At this point I'm personally ready to mark this issue as fixed, though I would point out the logs for the controller are still different from almost every other controller (i.e. listing `kind=` instead of something like `kind=IAMPolicyMember`.) At this time it appears to be cosmetic so I don't care.

**Comment by jcanseco** [comment] 2021-01-11 19:11
Hi @snuggie12, awesome, I'm glad to hear that your issue has been resolved. Closing this issue now then.

**Closed by jcanseco** 2021-01-11 19:11 UTC
Labels: bug
