### ISSUE TITLE
Renaming a Bigtable Instance, deletes the instance but fails to create new.

### ISSUE THREAD

**Issue by balaji** [GoogleCloudPlatform/k8s-config-connector#174] opened 2020-05-12 13:57 UTC
**Describe the bug**
Renaming a `BigtableInstance` instance that is already managed, deletes the instance, but fails to create a new instance.

**ConfigConnector Version**
1.7.1

**To Reproduce**
* Create a new Bigtable Instance using KCC
* Rename the instance in the yaml.

Expected:
Old instance to be deleted and a new one created.

Actual:
Old instance is deleted but creating a new instance fails with the following error message:
```Update call failed: error applying desired state: Error creating instance. rpc error: code = AlreadyExists desc = Cannot re-create cluster 'gew-cluster' in a different instance```

*YAML snippets:*

```yaml
apiVersion: bigtable.cnrm.cloud.google.com/v1beta1
kind: BigtableInstance
metadata:
  name: test-instance
  namespace: bigtable-playground
spec:
  displayName: test instance
  instanceType: PRODUCTION
  cluster:
  - clusterId: gew-cluster
    zone: europe-west1-d
    numNodes: 1
  - clusterId: guc-cluster
    zone: us-central1-b
    numNodes: 1
```

**Comment by kibbles-n-bytes** [comment] 2020-05-12 23:05
Hey @balaji,

I've been playing around with this scenario, and I think there's a bit of a misunderstanding around Kubernetes and `metadata.name`. Config Connector here is not actually deleting and recreating anything; what's happening is that KCC is trying to make a copy of the instance but with a new name, and the underlying API is saying that it can't create something that already exists.

When you change the `metadata.name` in the YAML, this means to Kubernetes that this is an entirely separate resource in etcd. If you `kubectl apply` it, Kubernetes wouldn't actually rename; it creates a second resource in your cluster that triggers KCC to then try to create a second Bigtable instance on Google Cloud. If you run `kubectl get` on the first resource, you should still see it around. This is why the error string says `error creating instance` instead of something like `error updating instance`.

In this case, it's not able to create this second instance, as a restriction on the underlying Bigtable API is that cluster IDs in Bigtable are project-scoped and cannot be re-used between instances. The error message coming from the underlying API I think here is a bit misleading: it says `Cannot re-create cluster`, which to me would normally imply something was deleted first, but in this case it should be interpreted as saying "cannot create a cluster which was already created (i.e. already exists)". We try to pass back explicitly what the underlying API gives as its error and don't do any editorializing on top.

I was not able to replicate any resource destruction in this scenario via directly `kubectl apply`ing to a cluster with KCC installed. If you can confirm the instance *was* deleted, this likely is due to a layer on top of the KCC and the cluster, perhaps as part of a GitOps pipeline. With this, I could see a rename in the YAML being interpreted by the *pipeline* (not KCC) as a delete of the old resource and a create of the new resource. With this, though, I would expect the second resource creation to go through, although it may be blocked temporarily by the situation described above if ordering happens to create the second resource before the first one is deleted. KCC should be re-reconciling in this case and eventually successfully create the second instance once the first instance successfully deletes and the cluster IDs are no longer reserved.

**Comment by Bj0rnen** [comment] 2020-05-13 14:51
Hi, I can confirm that this is part of pipeline running on top of KCC, which is why deletion of the original instance is issued.

I think what you've added in you edit is a satisfactory explanation of why we perceived KCC as being "stuck". Thank you for clearing that up!

But then, would it at all be possible to indicate this in the status message (upon `kubectl describe`)? Ideally, if that is known to be the cause, then explain that. But even if that can't be known, it would still help a lot to see a note that "this might be caused by a deleted Bigtable instance being preserved after deletion in case it needs to be recovered".

**Comment by kibbles-n-bytes** [comment] 2020-05-13 15:17
Hey @Bj0rnen, in this case, the error message is applicable to not just KCC customers, but any Bigtable customer that gets into a situation where they wanted to delete their first instance and create a new instance with the same cluster IDs, and so we feel that those sort of beneficial changes for all customers should be made at the underlying API layer. If the error message is updated there, it'll be reflected in KCC, as well as Deployment Manager, Terraform, gcloud, any any other tooling customers are using. Would it be alright if you requested directly to the Bigtable team?

**Comment by kibbles-n-bytes** [comment] 2020-05-13 15:21
Switching the type of issue over to `question`, as the behavior here is working as intended and is more-so a discussion around Kubernetes resource behavior, Bigtable API behavior, and GitOps flows.

**Comment by Bj0rnen** [comment] 2020-05-27 08:52
Thanks for clarifying this issue for us! We will bring this topic up in a meeting with the Bigtable team.

We can close this issue now.

**Closed** 2020-05-27 23:10 UTC
Labels: question
