### ISSUE TITLE
Error when creating a new service account in managed project

### ISSUE THREAD

**Issue by LeoHexspoor** [GoogleCloudPlatform/k8s-config-connector#278] opened 2020-09-17 12:33 UTC
**Describe the bug**
I'm unable to create a new service account from a new namespace that is managing a specific project with a separate service account.

After creating the new Service Account it gets the following status:
```Update call failed: error fetching live state: error reading underlying resource: Error when reading or editing Service Account "projects/nmt-config-connector-test/serviceAccounts/svc-example-service@nmt-config-connector-test.iam.gserviceaccount.com": Get "https://iam.googleapis.com/v1/projects/nmt-config-connector-test/serviceAccounts/svc-example-service@nmt-config-connector-test.iam.gserviceaccount.com?alt=json&prettyPrint=false": compute: Received 400 `Annotated service account must be in format of '[SA-NAME]@[PROJECT-ID].iam.gserviceaccount.com', '[SA_NAME]@appspot.gserviceaccount.com' or '[SA_NAME]@developer.gserviceaccount.com'```

Looking at the controller logs I see the same error:
```json
{
    "controller": "iamserviceaccount-controller",
    "error": "Update call failed: error fetching live state: error reading underlying resource: Error when reading or editing Service Account \"projects/nmt-config-connector-test/serviceAccounts/svc-example-service@nmt-config-connector-test.iam.gserviceaccount.com\": Get \"https://iam.googleapis.com/v1/projects/nmt-config-connector-test/serviceAccounts/svc-example-service@nmt-config-connector-test.iam.gserviceaccount.com?alt=json&prettyPrint=false\": compute: Received 400 `Annotated service account must be in format of '[SA-NAME]@[PROJECT-ID].iam.gserviceaccount.com', '[SA_NAME]@appspot.gserviceaccount.com' or '[SA_NAME]@developer.gserviceaccount.com'\n`",
    "level": "error",
    "logger": "controller-runtime.controller",
    "msg": "Reconciler error",
    "request": "cc-nmt-config-connector-test/svc-example-service",
    "stacktrace": "cnrm.googlesource.com/cnrm/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/github.com/go-logr/zapr/zapr.go:128\ncnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258\ncnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\ncnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\ncnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\ncnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\ncnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ncnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90",
    "ts": 1600342649.8798952
}
```

**ConfigConnector Version**
1.15, installed via GKE Add-on in a 1.16 GKE cluster.

**To Reproduce**
*Steps to reproduce the behavior:*
1. Create a new Service Account in host project with owner role in managed project
2. Create a new namespace
3. Deploy a new ConfigConnectorContext using the new GSA
4. Annotate namespace & ConfigConnectorContext so the managed project is the default
5. Deploy new Service Account in new namespace

*YAML snippets:*

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: svc-example-service
spec:
  displayName: Example Service Account
```

Note that I can create service accounts in the host project/namespace without problems.

**Comment by spew** [comment] 2020-09-21 14:09
Hi @LeoHexspoor thanks for the detailed reproduction steps. We will be looking into this issue and let you know when we have a fix.

**Comment by spew** [comment] 2020-09-21 14:13
In this example is the host project `nmt-config-connector-test` or is that the managed project?

**Comment by LeoHexspoor** [comment] 2020-09-21 16:46
Hi @spew, thank you, that is the managed project.

**Comment by kibbles-n-bytes** [comment] 2020-10-27 16:27
Hey @LeoHexspoor , sorry for the delay in us getting back to you.

Unfortunately, I am unable to reproduce with the given steps. I did the following:

- Installed Config Connector in namespaced mode at version 1.15.0
- Created a `ConfigConnectorContext` specifying a service account email in the host project (same project where the cluster lives)
- Annotated the default namespace to say `project-id: [SERVICE_PROJECT_ID]` (where I want the resource to live)
- Use your exact YAML to create a sample IAM service account in the default namespace

And the resource went through fine and reached `UpToDate` quickly.

Your error message is a bit suspicious, because it specifies `compute` despite this being a purely IAM call. And it's talking about the "annotated service account". This implies to me this is not a scenario with this particular resource, but it's the workload identity binding being set up incorrectly.

Can you confirm that the service account email you specified in the `ConfigConnectorContext` is correct? It sounds like it's not matching the expected format for authenticating with workload identity. It should be of the form `[ACCOUNT_ID]@[PROJECT_ID].iam.gserviceaccount.com`. So mine looks like:

```
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  name: configconnectorcontext.core.cnrm.cloud.google.com
spec:
  googleServiceAccount: "cnrm-system@[MY_PROJECT].iam.gserviceaccount.com"
```

If you're missing the `.iam.` or some part of the string, it will not work.

Could you also confirm if you're able to create other resources in that namespace successfully, like a Pub/Sub topic or something trivial? If this is a problem with workload identity, it should apply to all resource types, and the fact it was an `IAMServiceAccount` that gave a service account-related error, or the Config Connector service account living in a different project, was a coincidence.

**Comment by kibbles-n-bytes** [comment] 2020-11-13 21:00
Going to close this out as it seems to be user error (see comment above).

**Closed by kibbles-n-bytes** 2020-11-13 21:00 UTC
Labels: bug
