### ISSUE TITLE
ComputeSSLCertificate definition mismatch with CRD

### ISSUE THREAD

**Issue by haorenfsa** [GoogleCloudPlatform/k8s-config-connector#1010] opened 2023-11-13 07:45 UTC
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/v1.97.0/pkg/clients/generated/apis/compute/v1beta1/computesslcertificate_types.go#L61
`ComputeSSLCertificate.spec.certificate.valueFrom.secretKeyRef`

According to the actual CRD, this field is not a  `ResourceRef`, but a `corev1.SecretKeySelector`

`ComputeSSLCertificate.spec.privatekey.valueFrom.secretKeyRef`  has the same problem

### Additional Diagnostic Information

 `k explain ComputeSSLCertificate.spec.certificate.valueFrom.secretKeyRef `

```
KIND:     ComputeSSLCertificate
VERSION:  compute.cnrm.cloud.google.com/v1beta1

RESOURCE: secretKeyRef <Object>

DESCRIPTION:
     Reference to a value with the given key in the given Secret in the
     resource's namespace.

FIELDS:
   key  <string> -required-
     Key that identifies the value to be extracted.

   name <string> -required-
     Name of the Secret to extract a value from.
```

### Kubernetes Cluster Version

not matters

### Config Connector Version

1.111.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

golang model error

**Comment by diviner524** [comment] 2023-11-13 18:30
@haorenfsa Yes this is caused by an incorrect assumption when determining resourceRef fields for the generated go client.

JFYI, the Go client is in a preview/alpha stage and we don't have people dedicated to fixing it yet. However, some users have taken a stab at fixing it, like:

https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/848

If you're interested in tackling this, please let us know! We'd be happy to review your Pull Request.

**Comment by haorenfsa** [comment] 2023-11-14 02:09
@diviner524  oh yes I'm glad to. Our projects are using config connector together with crossplane.

**Comment by haorenfsa** [comment] 2023-11-14 02:29
Took a glance at the code, looks like the go client code is generated from crd through the code under script/ , shall I start from there?

**Comment by haorenfsa** [comment] 2023-11-14 06:42
I think the best and simplest way is to keep the `ResourceRef`. The `ResourceRef` struct will have all the possible fields in a reference `kind, apiVersion, key, name, namespace, external`. 
There will be some redundant fields for some type, but it won't hurt.

**Comment by diviner524** [comment] 2023-12-08 20:08
This is fixed in:

https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1025

And released in:

https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.112.0

**Closed by diviner524** 2023-12-08 20:08 UTC
Labels: bug
