### ISSUE TITLE
Can StorageBucket name be overridden

### ISSUE THREAD

**Issue by RoryShively** [GoogleCloudPlatform/k8s-config-connector#183] opened 2020-05-21 16:00 UTC
Can the name of a StorageBucket be overridden? I need to use underscores in my bucket name as I migrate to using config connector but since the StorageBucket crd uses the name field for the bucket name and that has different name restrictions than GCP does I think I'm unable to.

Is there a way to do this by adding an annotation or something?

If I wanted to contribute to the project by adding this feature which github repo contains the controller code?

**Comment by RoryShively** [comment] 2020-05-21 19:53
Would be helpful to be able to override the name of the bucket create with an annotation such as
```
annotations:
    "cnrm.cloud.google.com/bucket-name": "name_with_underscore"
```

https://cloud.google.com/config-connector/docs/reference/resources#storagebucket

**Comment by AlexBulankou** [comment] 2020-05-22 12:42
Thanks for reporting. Marking as duplicate of https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/128.
We are tracking it as enhancement and will update the linked issue once we have more information. If you are tracking this issue with a customer support engineer, we'll also provide additional context to them directly.

**Comment by AlexBulankou** [comment] 2020-05-22 12:42
duplicate of #128

**Closed by AlexBulankou** 2020-05-22 12:42 UTC
Labels: question
