### ISSUE TITLE
Failure to delete ComputeTargetHTTPSProxy

### ISSUE THREAD

**Issue by mrsimo** [GoogleCloudPlatform/k8s-config-connector#430] opened 2021-03-18 11:22 UTC
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

When deleting a `ComputeTargetHTTPSProxy`, we see this error:

```
status:
  conditions:
  - lastTransitionTime: "2021-03-15T18:31:16Z"
    message: 'Delete call failed: error fetching live state: error converting resource
      config: error resolving value of target field of referenced resource compute.cnrm.cloud.google.com/v1beta1,
      Kind=ComputeTargetHTTPSProxy misty-surf/misty-surf-staging: referenced resource''s
      target field self_link is unsupported'
    reason: DeleteFailed
    status: "False"
    type: Ready
```

We've been running this setup for a while, there has been no change in config connector or kubernetes version that triggered this.

We have another cluster with the exact same setup, that deploys the same workloads, but doesn't exhibit this behavior.

### Kubernetes Cluster Version

```
Client Version: v1.19.7
Server Version: v1.18.12-gke.1210
```

### Config Connector Version

```
1.31.1
```

### Config Connector Mode

I don't get any output from the given command. It's a GKE cluster in the Regular Release Channel with Config Connector addon enabled.

## Log Output

On the cluster where this error happens (reverse time order):

```
{"severity":"error","logger":"controller-runtime.controller","msg":"Reconciler error","controller":"computetargethttpsproxy-controller","request":"misty-surf/misty-surf-staging","error":"Delete call failed: error fetching live state: error converting resource config: error resolving value of target field of referenced resource compute.cnrm.cloud.google.com/v1beta1, Kind=ComputeTargetHTTPSProxy misty-surf/misty-surf-staging: referenced resource's target field self_link is unsupported"}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"finalizing resource deletion","resource":{"namespace":"misty-surf","name":"misty-surf-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"starting reconcile","resource":{"namespace":"misty-surf","name":"misty-surf-staging"}}
```

On the cluster where this error doesn't happen:

```
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"resource not found in API server; finishing reconcile","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"successfully finished reconcile","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"starting reconcile","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"deleting underlying resource","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"finalizing resource deletion","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"starting reconcile","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"finalizing resource deletion","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"deletion defender has not yet been finalized; requeuing","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"starting reconcile","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"finalizing resource deletion","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"deletion defender has not yet been finalized; requeuing","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"starting reconcile","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"finalizing resource deletion","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"deletion defender has not yet been finalized; requeuing","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
{"severity":"info","logger":"computetargethttpsproxy-controller","msg":"starting reconcile","resource":{"namespace":"bold-grass","name":"bold-grass-staging"}}
```

### YAML snippets

This is the resource  from running `kubectl get ComputeTargetHTTPSProxy/misty-surf-staging -o yaml`

```yaml
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeTargetHTTPSProxy
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: harvesthq-staging
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"compute.cnrm.cloud.google.com/v1beta1","kind":"ComputeTargetHTTPSProxy","metadata":{"annotations":{},"labels":{"app":"staging","billing_bucket":"staging","component":"web","env":"staging"},"name":"misty-surf-staging","namespace":"misty-surf"},"spec":{"description":"staging-misty-surf/staging","location":"global","sslCertificates":[{"name":"misty-surf-staging"}],"sslPolicyRef":{"name":"misty-surf-staging"},"urlMapRef":{"name":"misty-surf-staging"}}}
  creationTimestamp: "2021-03-15T11:42:22Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2021-03-17T16:10:42Z"
  finalizers:
  - cnrm.cloud.google.com/finalizer
  generation: 181
  labels:
    app: staging
    billing_bucket: staging
    component: web
    env: staging
  managedFields:
  - apiVersion: compute.cnrm.cloud.google.com/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
          f:billing_bucket: {}
          f:component: {}
          f:env: {}
      f:spec:
        .: {}
        f:description: {}
        f:location: {}
        f:sslCertificates: {}
        f:sslPolicyRef:
          .: {}
          f:name: {}
        f:urlMapRef:
          .: {}
          f:name: {}
    manager: kubectl
    operation: Update
    time: "2021-03-15T11:42:22Z"
  - apiVersion: compute.cnrm.cloud.google.com/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"cnrm.cloud.google.com/finalizer": {}
      f:spec:
        f:quicOverride: {}
      f:status:
        .: {}
        f:conditions: {}
        f:creationTimestamp: {}
        f:proxyId: {}
        f:selfLink: {}
    manager: cnrm-controller-manager
    operation: Update
    time: "2021-03-18T11:16:47Z"
  name: misty-surf-staging
  namespace: misty-surf
  resourceVersion: "497555542"
  selfLink: /apis/compute.cnrm.cloud.google.com/v1beta1/namespaces/misty-surf/computetargethttpsproxies/misty-surf-staging
  uid: 85f1f2cc-7b1b-4aba-ac5a-035bf62400b3
spec:
  description: staging-misty-surf/staging
  location: global
  quicOverride: NONE
  sslCertificates:
  - name: misty-surf-staging
  sslPolicyRef:
    name: misty-surf-staging
  urlMapRef:
    name: misty-surf-staging
status:
  conditions:
  - lastTransitionTime: "2021-03-15T18:31:16Z"
    message: 'Delete call failed: error fetching live state: error converting resource
      config: error resolving value of target field of referenced resource compute.cnrm.cloud.google.com/v1beta1,
      Kind=ComputeTargetHTTPSProxy misty-surf/misty-surf-staging: referenced resource''s
      target field self_link is unsupported'
    reason: DeleteFailed
    status: "False"
    type: Ready
  creationTimestamp: "2021-03-15T04:42:45.691-07:00"
  proxyId: 4458361908275377700
  selfLink: https://www.googleapis.com/compute/v1/projects/harvesthq-staging/global/targetHttpsProxies/misty-surf-staging
```

**Comment by jcanseco** [comment] 2021-03-22 19:59
Hi @mrsimo, sorry for the late response. Looking into the issue now.

Unfortunately the error message is misleading. It says it's trying (and failing) to resolve the referenced `ComputeTargetHTTPSProxy` resource, but it's actually trying to resolve a different kind of resource instead. This error message was wrong and was fixed in a newer version of Config Connector, but unfortunately not on your version (`1.31.1`).

With that said, can you check if your referenced resources have a `status.selfLink` (or a `status` block at all)?

1. `kubectl get computesslcertificate -n misty-surf misty-surf-staging -o yaml`
1. `kubectl get computeurlmap -n misty-surf misty-surf-staging -o yaml`
1. `kubectl get computesslpolicy -n misty-surf misty-surf-staging -o yaml`

**Comment by mrsimo** [comment] 2021-03-23 10:23
HI @jcanseco. Thanks a lot for the update! Wanted to give a bit of context on this. This is part of our staging system, and we create a full environment per namespace, with a random name (like the `misty-surf` from the issue). These are spread on two clusters, and these "failed" stagings had been worked on something new related to our load balancing configuration, but chance had it that all had come from the same cluster, so it was misleading.

I had to clean them up before I saw your message, unfortunately, but these "failed" stagings had indeed a few broken resources. I had to do a bunch of manual deletions (via `glcloud`) before the `kubectl delete` commands worked again. I'll try to reproduce the issue again and see if I can give you the details you need. It was all very confusing, sorry.

**Comment by jcanseco** [comment] 2021-03-23 14:34
Hi @mrsimo, that's no problem at all. The context you gave is quite helpful actually and will help with reproduction on our side :)

**Comment by mrsimo** [comment] 2021-03-23 15:45
Haven't been able to reproduce, sorry! From talking to the engineer working on this, any of these could have been the culprit:

* The `ComputeURLMap` might have been pointing somewhere to a `ComputeBackendBucket` that didn't exist. There was an actual `ComputeBackendBucket`, but with a different name (I tried this, but deletion did work, so I don't know if that was the problem).
* We're hitting some form of https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/313, which means that updates to a `ComputeURLMap` are failing completely. The engineer says that he added the `cnrm.cloud.google.com/deletion-policy: abandon` annotation, deleted the k8s resource and deployed the URLMap again to see if it worked.
* When these stagings get deleted, they delete objects in this order (I see now we should probably delete the `StorageBucket` before the `ComputeBackendBucket`, but anyhow it was getting stuck before that point):
  - ComputeForwardingRule
  - ComputeTargetHTTPProxy
  - ComputeTargetHTTPSProxy
  - ComputeSSLPolicy
  - ComputeSSLCertificate
  - ComputeAddress
  - ComputeURLMap
  - ComputeBackendService
  - ComputeBackendBucket
  - ComputeHealthCheck

Sorry I don't have a way to reproduce, we don't have an issue on our side at the moment, I'd understand if you want to close.

**Comment by jcanseco** [comment] 2021-03-23 21:31
Hi @mrsimo, that's no problem at all, and thanks for taking the time to collect and share with us the details!

Let us mark this issue closed for now then since there is not enough information to reproduce the issue, and we were not able to reproduce the issue either.

If you ever face the issue again and find your resource being stuck in `DeleteFailed` with that error message, then please do let us know and we will resume the investigation!

**Closed by jcanseco** 2021-03-23 21:31 UTC
Labels: bug
