### ISSUE TITLE
Operator configconnector-operator fails to upgrade some CRDs in version 1.17.0

### ISSUE THREAD

**Issue by dflemstr** [GoogleCloudPlatform/k8s-config-connector#253] opened 2020-08-14 12:38 UTC
**Describe the bug**
When upgrading from version 1.13.1 to 1.17.0, the operator fails to apply the CRDs for some resources.

There are some CRD versions that remain on version 1.13.1:

```
$ kubectl get customresourcedefinitions -o json | jq '.items[]|select(.metadata.annotations."cnrm.cloud.google.com/version" == "1.13.1")|.spec.names.kind'
"IAMPolicy"
"IAMPolicyMember"
```

The operator crashes with this stacktrace:

```
2020-08-14T06:28:34.885Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "configconnector-controller", "request": "/configconnector.core.cnrm.cloud.google.com"}
2020-08-14T06:28:34.880Z	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"ConfigConnector","name":"configconnector.core.cnrm.cloud.google.com","uid":"e8f3126a-0c6d-4e76-bd21-f83b397b6f36","apiVersion":"core.cnrm.cloud.google.com/v1beta1","resourceVersion":"46248409"}, "reason": "UpdateFailed", "message": "error during reconciliation: error applying manifest: error from running kubectl apply: exit status 1"}
	/go/src/cnrm.googlesource.com/configconnector-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
cnrm.googlesource.com/configconnector-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until
	/go/src/cnrm.googlesource.com/configconnector-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
cnrm.googlesource.com/configconnector-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/src/cnrm.googlesource.com/configconnector-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156
cnrm.googlesource.com/configconnector-operator/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/src/cnrm.googlesource.com/configconnector-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155
cnrm.googlesource.com/configconnector-operator/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/src/cnrm.googlesource.com/configconnector-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211
cnrm.googlesource.com/configconnector-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/src/cnrm.googlesource.com/configconnector-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232
cnrm.googlesource.com/configconnector-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/src/cnrm.googlesource.com/configconnector-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256
cnrm.googlesource.com/configconnector-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/src/cnrm.googlesource.com/configconnector-operator/pkg/controllers/configconnector_controller.go:305
cnrm.googlesource.com/configconnector-operator/pkg/controllers.(*ConfigConnectorReconciler).Reconcile
	/go/src/cnrm.googlesource.com/configconnector-operator/vendor/sigs.k8s.io/kubebuilder-declarative-pattern/pkg/patterns/declarative/reconciler.go:106
cnrm.googlesource.com/configconnector-operator/vendor/sigs.k8s.io/kubebuilder-declarative-pattern/pkg/patterns/declarative.(*Reconciler).Reconcile
	/go/src/cnrm.googlesource.com/configconnector-operator/vendor/sigs.k8s.io/kubebuilder-declarative-pattern/pkg/patterns/declarative/reconciler.go:163
cnrm.googlesource.com/configconnector-operator/vendor/sigs.k8s.io/kubebuilder-declarative-pattern/pkg/patterns/declarative.(*Reconciler).reconcileExists
	/go/src/cnrm.googlesource.com/configconnector-operator/vendor/github.com/go-logr/zapr/zapr.go:128
cnrm.googlesource.com/configconnector-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error
2020-08-14T06:28:34.880Z	ERROR	applying manifest	{"error": "error from running kubectl apply: exit status 1"}
```

**ConfigConnector Version**
1.17.0

**Comment by caieo** [comment] 2020-08-14 21:33
Hi @dflemstr , sorry you ran into this. I was unable to reproduce this (I installed the operator at version 1.13.1 and tried upgrading it to 1.17.0) and did not see that those CRD versions remained at 1.13.1. I didn't have/apply any of those resources and it's possible there might be upgrade issues if you have existing IAMPolicy/IAMPolicyMember resources. Could you give me more details to help reproduce this? (did you have IAMPolicy & IAMPolicyMember resources that already existed?)

**Comment by dflemstr** [comment] 2020-08-17 07:41
@caieo yes, there were existing IAMPolicy/IAMPolicyMember resources in the cluster.  I was under the impression that, since there was no change in API version (`v1beta1`, which also remains the stored/served version), there would be no reason for existing resources to block an upgrade, since they shouldn't contain any breaking changes, and also no webhook conversion will take place.  We have many other resources in this cluster that are not `IAMPolicy`/`IAMPolicyMember` and their CRDs were updated successfully.

Since this is blocking a critical upgrade for us, we will probably end up manually applying the new CRDs, but before we do that we'd like to give you the chance to request additional debugging information in case you want to diagnose this later.  Below follow a few dumps of potentially useful information:


<details><summary>
<code>kubectl get customresourcedefinitions.apiextensions.k8s.io iampolicies.iam.cnrm.cloud.google.com -o yaml</code>
</summary>

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 1.13.1
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"cnrm.cloud.google.com/version":"1.13.1"},"creationTimestamp":null,"labels":{"cnrm.cloud.google.com/managed-by-kcc":"true","cnrm.cloud.google.com/system":"true","controller-tools.k8s.io":"1.0","core.cnrm.cloud.google.com/configconnector":"configconnector.core.cnrm.cloud.google.com"},"name":"iampolicies.iam.cnrm.cloud.google.com","ownerReferences":[{"apiVersion":"core.cnrm.cloud.google.com/v1beta1","blockOwnerDeletion":true,"controller":true,"kind":"ConfigConnector","name":"configconnector.core.cnrm.cloud.google.com","uid":"e8f3126a-0c6d-4e76-bd21-f83b397b6f36"}]},"spec":{"group":"iam.cnrm.cloud.google.com","names":{"kind":"IAMPolicy","plural":"iampolicies"},"scope":"Namespaced","validation":{"openAPIV3Schema":{"properties":{"apiVersion":{"description":"APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources","type":"string"},"kind":{"description":"Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds","type":"string"},"metadata":{"type":"object"},"spec":{"properties":{"bindings":{"description":"Optional. The list of IAM bindings.","items":{"properties":{"condition":{"description":"Optional. The condition under which the binding applies.","properties":{"description":{"type":"string"},"expression":{"type":"string"},"title":{"type":"string"}},"required":["title","expression"],"type":"object"},"members":{"description":"Optional. The list of IAM users to be bound to the role.","items":{"pattern":"^(user|serviceAccount|group|domain|projectEditor|projectOwner):.+|allUsers|allAuthenticatedUsers$","type":"string"},"pattern":"^(user|serviceAccount|group|domain|projectEditor|projectOwner):.+|allUsers|allAuthenticatedUsers$","type":"array"},"role":{"description":"Required. The role to bind the users to.","pattern":"^((projects|organizations)/[^/]+/)?roles/[\w_\.]+$","type":"string"}},"required":["role"],"type":"object"},"type":"array"},"resourceRef":{"description":"Required. The GCP resource to set the IAM policy on.","oneOf":[{"not":{"required":["external"]},"required":["name"]},{"not":{"anyOf":[{"required":["name"]},{"required":["namespace"]}]},"required":["external"]},{"not":{"anyOf":[{"required":["name"]},{"required":["namespace"]},{"required":["apiVersion"]},{"required":["external"]}]}}],"properties":{"apiVersion":{"type":"string"},"external":{"type":"string"},"kind":{"type":"string"},"name":{"type":"string"},"namespace":{"type":"string"}},"required":["kind"],"type":"object"}},"required":["resourceRef"],"type":"object"},"status":{"properties":{"conditions":{"description":"Conditions represents the latest available observations of the IAM policy's current state.","items":{"properties":{"lastTransitionTime":{"description":"Last time the condition transitioned from one status to another.","type":"string"},"message":{"description":"Human-readable message indicating details about last transition.","type":"string"},"reason":{"description":"Unique, one-word, CamelCase reason for the condition's last transition.","type":"string"},"status":{"description":"Status is the status of the condition. Can be True, False, Unknown.","type":"string"},"type":{"description":"Type is the type of the condition.","type":"string"}},"type":"object"},"type":"array"}},"type":"object"}},"type":"object"}},"version":"v1beta1"},"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}}
  creationTimestamp: "2020-06-11T13:47:47Z"
  generation: 3
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
    controller-tools.k8s.io: "1.0"
    core.cnrm.cloud.google.com/configconnector: configconnector.core.cnrm.cloud.google.com
  name: iampolicies.iam.cnrm.cloud.google.com
  ownerReferences:
  - apiVersion: core.cnrm.cloud.google.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ConfigConnector
    name: configconnector.core.cnrm.cloud.google.com
    uid: e8f3126a-0c6d-4e76-bd21-f83b397b6f36
  resourceVersion: "17693339"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/iampolicies.iam.cnrm.cloud.google.com
  uid: 17974089-48f8-4acc-ab0c-5b291efc89e6
spec:
  conversion:
    strategy: None
  group: iam.cnrm.cloud.google.com
  names:
    kind: IAMPolicy
    listKind: IAMPolicyList
    plural: iampolicies
    singular: iampolicy
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              bindings:
                description: Optional. The list of IAM bindings.
                items:
                  properties:
                    condition:
                      description: Optional. The condition under which the binding
                        applies.
                      properties:
                        description:
                          type: string
                        expression:
                          type: string
                        title:
                          type: string
                      required:
                      - title
                      - expression
                      type: object
                    members:
                      description: Optional. The list of IAM users to be bound to
                        the role.
                      items:
                        pattern: ^(user|serviceAccount|group|domain|projectEditor|projectOwner):.+|allUsers|allAuthenticatedUsers$
                        type: string
                      pattern: ^(user|serviceAccount|group|domain|projectEditor|projectOwner):.+|allUsers|allAuthenticatedUsers$
                      type: array
                    role:
                      description: Required. The role to bind the users to.
                      pattern: ^((projects|organizations)/[^/]+/)?roles/[\w_\.]+$
                      type: string
                  required:
                  - role
                  type: object
                type: array
              resourceRef:
                description: Required. The GCP resource to set the IAM policy on.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                    - required:
                      - apiVersion
                    - required:
                      - external
                properties:
                  apiVersion:
                    type: string
                  external:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - kind
                type: object
            required:
            - resourceRef
            type: object
          status:
            properties:
              conditions:
                description: Conditions represents the latest available observations
                  of the IAM policy's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: IAMPolicy
    listKind: IAMPolicyList
    plural: iampolicies
    singular: iampolicy
  conditions:
  - lastTransitionTime: "2020-06-11T13:47:47Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2020-06-11T13:47:47Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
```

</details>

<details><summary>
<code>kubectl get customresourcedefinitions.apiextensions.k8s.io iampolicymembers.iam.cnrm.cloud.google.com -o yaml</code>
</summary>

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.cloud.google.com/version: 1.13.1
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"cnrm.cloud.google.com/version":"1.13.1"},"creationTimestamp":null,"labels":{"cnrm.cloud.google.com/managed-by-kcc":"true","cnrm.cloud.google.com/system":"true","controller-tools.k8s.io":"1.0","core.cnrm.cloud.google.com/configconnector":"configconnector.core.cnrm.cloud.google.com"},"name":"iampolicymembers.iam.cnrm.cloud.google.com","ownerReferences":[{"apiVersion":"core.cnrm.cloud.google.com/v1beta1","blockOwnerDeletion":true,"controller":true,"kind":"ConfigConnector","name":"configconnector.core.cnrm.cloud.google.com","uid":"e8f3126a-0c6d-4e76-bd21-f83b397b6f36"}]},"spec":{"group":"iam.cnrm.cloud.google.com","names":{"kind":"IAMPolicyMember","plural":"iampolicymembers"},"scope":"Namespaced","validation":{"openAPIV3Schema":{"properties":{"apiVersion":{"description":"APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources","type":"string"},"kind":{"description":"Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds","type":"string"},"metadata":{"type":"object"},"spec":{"properties":{"condition":{"description":"Optional. The condition under which the binding applies.","properties":{"description":{"type":"string"},"expression":{"type":"string"},"title":{"type":"string"}},"required":["title","expression"],"type":"object"},"member":{"description":"Required. The list of IAM identities to be bound to the role","pattern":"^(user|serviceAccount|group|domain|projectEditor|projectOwner):.+|allUsers|allAuthenticatedUsers$","type":"string"},"resourceRef":{"description":"Required. The GCP resource to set the IAM policy on.","oneOf":[{"not":{"required":["external"]},"required":["name"]},{"not":{"anyOf":[{"required":["name"]},{"required":["namespace"]}]},"required":["external"]},{"not":{"anyOf":[{"required":["name"]},{"required":["namespace"]},{"required":["apiVersion"]},{"required":["external"]}]}}],"properties":{"apiVersion":{"type":"string"},"external":{"type":"string"},"kind":{"type":"string"},"name":{"type":"string"},"namespace":{"type":"string"}},"required":["kind"],"type":"object"},"role":{"description":"Required. The role for which the Member will be bound.","pattern":"^((projects|organizations)/[^/]+/)?roles/[\w_\.]+$","type":"string"}},"required":["resourceRef","member","role"],"type":"object"},"status":{"properties":{"conditions":{"description":"Conditions represents the latest available observations of the IAM policy's current state.","items":{"properties":{"lastTransitionTime":{"description":"Last time the condition transitioned from one status to another.","type":"string"},"message":{"description":"Human-readable message indicating details about last transition.","type":"string"},"reason":{"description":"Unique, one-word, CamelCase reason for the condition's last transition.","type":"string"},"status":{"description":"Status is the status of the condition. Can be True, False, Unknown.","type":"string"},"type":{"description":"Type is the type of the condition.","type":"string"}},"type":"object"},"type":"array"}},"type":"object"}},"type":"object"}},"version":"v1beta1"},"status":{"acceptedNames":{"kind":"","plural":""},"conditions":[],"storedVersions":[]}}
  creationTimestamp: "2020-06-11T13:47:47Z"
  generation: 3
  labels:
    cnrm.cloud.google.com/managed-by-kcc: "true"
    cnrm.cloud.google.com/system: "true"
    controller-tools.k8s.io: "1.0"
    core.cnrm.cloud.google.com/configconnector: configconnector.core.cnrm.cloud.google.com
  name: iampolicymembers.iam.cnrm.cloud.google.com
  ownerReferences:
  - apiVersion: core.cnrm.cloud.google.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ConfigConnector
    name: configconnector.core.cnrm.cloud.google.com
    uid: e8f3126a-0c6d-4e76-bd21-f83b397b6f36
  resourceVersion: "17693559"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/iampolicymembers.iam.cnrm.cloud.google.com
  uid: 91fc2e2a-2edf-4f12-84c0-a1fe8881d48c
spec:
  conversion:
    strategy: None
  group: iam.cnrm.cloud.google.com
  names:
    kind: IAMPolicyMember
    listKind: IAMPolicyMemberList
    plural: iampolicymembers
    singular: iampolicymember
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              condition:
                description: Optional. The condition under which the binding applies.
                properties:
                  description:
                    type: string
                  expression:
                    type: string
                  title:
                    type: string
                required:
                - title
                - expression
                type: object
              member:
                description: Required. The list of IAM identities to be bound to the
                  role
                pattern: ^(user|serviceAccount|group|domain|projectEditor|projectOwner):.+|allUsers|allAuthenticatedUsers$
                type: string
              resourceRef:
                description: Required. The GCP resource to set the IAM policy on.
                oneOf:
                - not:
                    required:
                    - external
                  required:
                  - name
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                  required:
                  - external
                - not:
                    anyOf:
                    - required:
                      - name
                    - required:
                      - namespace
                    - required:
                      - apiVersion
                    - required:
                      - external
                properties:
                  apiVersion:
                    type: string
                  external:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - kind
                type: object
              role:
                description: Required. The role for which the Member will be bound.
                pattern: ^((projects|organizations)/[^/]+/)?roles/[\w_\.]+$
                type: string
            required:
            - resourceRef
            - member
            - role
            type: object
          status:
            properties:
              conditions:
                description: Conditions represents the latest available observations
                  of the IAM policy's current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition.
                      type: string
                    reason:
                      description: Unique, one-word, CamelCase reason for the condition's
                        last transition.
                      type: string
                    status:
                      description: Status is the status of the condition. Can be True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the condition.
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: IAMPolicyMember
    listKind: IAMPolicyMemberList
    plural: iampolicymembers
    singular: iampolicymember
  conditions:
  - lastTransitionTime: "2020-06-11T13:47:47Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2020-06-11T13:47:47Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
```

</details>

Except for the log output in the initial description of this issue I'm not sure what else we could attach here?

**Comment by fsommar** [comment] 2020-08-17 12:33
@caieo it's most likely that the cause here is a manual edit of the CRDs when we were still on the previous version; I edited the role regex to support referencing organization-based custom roles (see the latest comments in #78). It seems that a patched resource cannot be properly updated by the operator-based installation method.

**Comment by jcanseco** [comment] 2020-08-18 22:34
Hi all, thanks, we'll look into reproducing the issue since this does seem like strange behavior. We'll let you know when we have updates/questions.

**Comment by jcanseco** [comment] 2020-09-08 18:28
Hi all, we looked into reproducing this issue, but was still unable to. KCC v1.19.1 updated the IAM roles regex to support organization roles, so we're hoping that there would no longer be a need to manually patch CRDs. If you were to face this issue again, please do let us know. Otherwise, we'll be closing this issue for now if that's ok since there isn't much else for us to go on.

**Closed by jcanseco** 2020-09-08 18:28 UTC
Labels: bug
