### ISSUE TITLE
Error: Update call failed: invalid mutation to initialNodeCount, despite unchanged initialNodeCount

### ISSUE THREAD

**Issue by jonnylangefeld** [GoogleCloudPlatform/k8s-config-connector#165] opened 2020-05-05 19:46 UTC
**Describe the bug**
After changing the `nodeCount` on a containernodepool resource, I get the error `Update call failed: the desired mutation for the following field(s) is invalid: [initialNodeCount]` in the events of the resource.
This happens in particular when a containernodepool is created with `autoscaling` and then edited to use `nodeCount` instead of `autoscaling`

**ConfigConnector Version**
`1.7.0`

**To Reproduce**
- create containernodepool resource with autoscaling (use yaml below)
- `kubectl edit` the containernodepool, remove autoscaling and change `nodeCount`
- do this last step again (this is when it fails). 
- check `kubectl describe` on the containernodepool, that's where the error is

*YAML snippets:*

```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: <project>
  name: sample-nodepool-green
  namespace: default
spec:
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 5
  initialNodeCount: 1
  clusterRef:
    external: <cluster-ref>
  location: us-central1
  nodeLocations:
    - us-central1-a
  maxPodsPerNode: 110
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    imageType: COS
    machineType: n1-standard-1
    metadata:
      additionalProperties: ""
      disable-legacy-endpoints: "true"
    minCpuPlatform: Intel Skylake
    oauthScopes:
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring
    serviceAccountRef:
      external: default
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
  upgradeSettings:
    maxSurge: 1
    maxUnavailable: 0
  version: 1.15.11-gke.11
```

**Comment by nitishkrishna** [comment] 2020-05-07 18:24
I work with Jonny and we have some additional information to share:

We tried to workaround the bug above by **removing initialNodeCount from the CRD.** After this we did not hit the update bug but we see another strange issue:

For this bug, let's assume that all we want to do is use ConfigConnector to create ContainerNodePools and then migrate pods between two of them.

We do this by first creating a "source" Node Pool which is empty at first and set to Autoscale. We scale it up with our test workload.
We then create a second "destination" Node Pool which is empty at first and set to Autoscale. We turn off autoscaling on the source NP and set the NodeCount manually to the current value.
We then keep scaling down the source NP by reducing the NodeCount on it one at a time.
Eventually we have an empty source NP and a fully scaled up destination NP.

Now to the strangeness:
The "destination" node Pool of this migration was created with ConfigConnector with autoscaling turned on and initalNodeCount never set (we can't set it because it isn't in the CRD).

This "destination" node Pool was allowed to autoscale up with the pods from the "source" node pool that we scaled down manually using nodeCount.

Once it was fully scaled up, we noticed that **initialNodeCount was set on that NodePool** by using the API describe command:

```
curl -s -H "Authorization: Bearer $(gcloud auth print-access-token)" -H "Content-Type: application/json" 

https://container.googleapis.com/v1/projects/<project>/locations/<region>/clusters/<cluster>/nodePools/sample-nodepool-green | jq

{
  "name": "sample-nodepool-green",
  "config":
    {
        ...
        "initialNodeCount": 2,
        "autoscaling": { "enabled": true, "minNodeCount": 1, "maxNodeCount": 6 },
        "status": "RUNNING",
        ...
    }
}
```

Clearly, ConfigConnector is not setting this field explicitly because we do not provide it in our Spec. 
Additionally, the node pool was **constantly resizing down to 2 [initialNodeCount]** and back up **even though NodeCount was never set on that NodePool**.

We have also been in touch with Google Support about the above issue and have given them this broken nodePool to debug.

We are able to re-create this issue **only with ConfigConnector** and didn't see it when using the GCP API directly.

**Comment by tonybenchsci** [comment] 2020-05-28 21:17
@kibbles-n-bytes Does KCC v1.10.0 fix this?

**Comment by jonnylangefeld** [comment] 2020-05-28 22:03
We were told by @kibbles-n-bytes that with tomorrows release (05/29/2020) this will be fixed.

**Comment by kibbles-n-bytes** [comment] 2020-05-30 17:12
Hey @jonnylangefeld and @tonybenchsci , the 1.11.0 release yesterday should alleviate these issues you're seeing around manually resizing and autoscaling node pools represented via `ContainerNodePool`. It introduces the following patches:
- treats `spec.initialNodeCount` as GCP-managed unless it is explicitly present in your `last-applied-configuration`
- treats `spec.nodeCount` as GCP-managed when autoscaling is enabled unless it is explicitly present in your `last-applied-configuration`.

Note that it is now no longer recommended to explicitly set `spec.initialNodeCount`, and we no longer do so as part of our samples. Although for backwards-compatibility purposes it still is able to be used to set the initial node count, it is recommended that you use exclusively `spec.nodeCount` for both the initial size setting and subsequent resizing of node pools (in essence treating `spec.initialNodeCount` as output-only).

Please let us know if there's still any friction around this scenario; I'll leave this issue open until you can verify things are working as intended.

**Comment by tonybenchsci** [comment] 2020-05-30 18:10
Thanks @kibbles-n-bytes :) Question: What does `spec.initialNodeCount` on `ContainerCluster` CRD do? Is that only for the default-node-pool, and isn't used if we have annotation `cnrm.cloud.google.com/remove-default-node-pool: "true"` ?

**Comment by kibbles-n-bytes** [comment] 2020-06-03 15:23
Hey @tonybenchsci :
1. No, `spec.initialNodeCount` on `ContainerNodePool` is not mutable from the perspective of the user. Only the system is able to update it, which is in line with how the GKE API treats it. Please do not use it at all in your config, as `spec.nodeCount` is able to be used to set the initial value as well.
2. `spec.initialNodeCount` on `ContainerCluster` sets the initial node count for the default node pool, and is pinned forever to that value no matter how things change underneath it (this is in behavior is different than `initialNodeCount` on the node pools, which is not pinned and changes when node pools are manually resized). If you use `remove-default-node-pool: "true"`, its value in effect does not matter. We'd like to push customers away from using the default node pool at all, and will likely make `initialNodeCount` default to 1 and `remove-default-node-pool` default to `true` in a future version bump, so that your `ContainerCluster` config does not have to worry about the default node pool at all and can be focused on exclusively cluster-scoped information.

**Comment by tonybenchsci** [comment] 2020-06-03 15:27
> Hey @tonybenchsci :
> 
>     1. No, `spec.initialNodeCount` on `ContainerNodePool` is not mutable from the perspective of the user. Only the system is able to update it, which is in line with how the GKE API treats it. Please do not use it at all in your config, as `spec.nodeCount` is able to be used to set the initial value as well.
> 
>     2. `spec.initialNodeCount` on `ContainerCluster` sets the initial node count for the default node pool, and is pinned forever to that value no matter how things change underneath it (this is in behavior is different than `initialNodeCount` on the node pools, which is not pinned and changes when node pools are manually resized). If you use `remove-default-node-pool: "true"`, its value in effect does not matter. We'd like to push customers away from using the default node pool at all, and will likely make `initialNodeCount` default to 1 and `remove-default-node-pool` default to `true` in a future version bump, so that your `ContainerCluster` config does not have to worry about the default node pool at all and can be focused on exclusively cluster-scoped information.

Thanks a bunch @kibbles-n-bytes !

**Comment by jonnylangefeld** [comment] 2020-06-29 22:42
Hi @kibbles-n-bytes,

we had now some amount of testing with version 1.11.1, however we still get overwritten for `initialNodeCount` even though it's present in the `last-applied-configuration` (see highlights in screenshot)
![Screen Shot 2020-06-29 at 3 39 54 PM](https://user-images.githubusercontent.com/18717376/86063035-c9769b00-ba1e-11ea-810c-60896d928d24.png)
The value 4 was never set by us.
This way a controller would get triggered to reconcile cause there is a diff, but run into an error because `initialNodeCount` is immutable.

**Comment by kibbles-n-bytes** [comment] 2020-07-07 18:46
Hey Jonny,

Let me first clarify our intentions: Please do not use `spec.initialNodeCount` in any capacity anymore as part of your flows. Any attempt to manually set the node count should now be done through `spec.nodeCount`. The field is now considered purely vestigial, and we intend to move it from spec to status as informational-only in a subsequent version bump. We keep it today only for backwards-compatibility purposes in order to not break workflows that currently rely on using its value to set the node count on node pool creation.

As part of your flows, please update them to conform with the following:

- If you are using `kubectl apply` to create node pools, please ensure that your configuration files use `spec.nodeCount` and not `spec.initialNodeCount` in order to specify the desired initial node count. Both client-side and server-side apply will then ensure that the property changing in the API server is never detected as an unintentional drift.
  - As a side-note, please do not manually set `kubectl.kubernetes.io/last-applied-configuration`; this annotation should be considered an implementation detail of kubectl, and any reference to it by us is meant more as us trying to be clear about our own implementation. My referencing it earlier may have caused more confusion than clarification, though; sorry about that.
- If you are making direct requests to the API server (e.g. via curl or client libraries), please ensure that no mutations are triggered on this field. If you are doing a PUT request, please ensure that you are doing a read->modify->write and always preserve the value that was read. 0 and not present are considered distinct values and cannot be used interchangeably, so languages like Go should use an `*int64` type if using custom structs.
- Please do not write controllers that rely on having to ever mutate the value in `spec.initialNodeCount`. In order to avoid asynchronous errors (which *would* occur on any intentional mutation to the field), we reject changes to this field synchronously from identities other than our controller.
  * If you are trying to blanket-wrap our resource with a CRD of your own, I'd recommend one of the following approaches:
    1) If you are trying to keep our resource in sync with yours, perhaps use `PATCH` with Apply semantics. Apply semantics treat not found always different as the zero value, and so you will need to have your controller be able to handle this with nullable values for all types. If you want to use `PUT` with mostly non-nullable, proto3-like Go struct semantics, ensure that zero values from your layer are ignored when making the appropriate modifications after the read and treat at least this field as nullable with a type of `*int64`.
    1) If you are trying to recreate something like a Deployment's `spec.podTemplate`, also recreate the Deployment's immutable infrastructure flow by deleting and recreating underlying resources as part of a template change.

------

With that, the following should be considered *only as implementation details* and not needed to be understood when using our resource. Please do not read too much into any of this, and let's only discuss how we intend for the resource to be used.

- If there is a value specified in `spec.initialNodeCount` when attempting to create a node pool on GKE, we will always use its value. If `spec.nodeCount` and `spec.initialNodeCount` are specified during creation, this is an error.
- After every reconcile, `spec.initialNodeCount` will always be updated to the value present on GKE.
- When determining what mutation to do to GKE during a reconcile, we do the following:
  - If a value is present for `spec.initialNodeCount` in the `kubectl.kubernetes.io/last-applied-configuration`, we will treat the resource's `spec.initialNodeCount` (non-annotation) value as the desired state for GCP; if `spec.initialNodeCount` does not match what is on GCP, this will *always error*.
    - I agree using the actual spec value here and not the annotation value for this particular field is weird. This was an attempt with other fields to prevent accidental clobbering of values that should be considered semantically the same: i.e. a node version in the apply of `1.16` vs. a "defaulted" node version in the spec post-reconcile of `1.16.X-gke.Y`, while still picking up apply mutations from that to, say, `1.17` (since kubectl will set both the annotation value and the spec value). It should be considered irrelevant for `spec.initialNodeCount`.

Since a reconciliation of `spec.nodeCount` is a trigger for the updated value of `initialNodeCount` as a side-effect, and it's not happening out-of-band as part of, say, GKE auto-versing-upgrading, that means this field can never really be considered truly fully "k8s-managed" today and different from the other GCP fields. Sorry about that, my initial statement is misleading in that regard. Please follow the guidance above to not have this negatively affect you.

**Comment by toumorokoshi** [comment] 2020-11-25 22:30
Hi! I'm going to close this issue since there hasn't been a discussion in a while, but please re-open if kibbles-n-bytes recommendations do not work.

**Closed by toumorokoshi** 2020-11-25 22:30 UTC
Labels: bug
